### ISSUE TITLE
Cannot delete/replace packages that fail validation

### ISSUE THREAD

**Issue by dotMorten** [NuGet/NuGetGallery#6014] opened 2018-05-30 23:37 UTC
If you upload a package that isn't signed with the right certificate, the package will fail validation as expected:

![image](https://user-images.githubusercontent.com/1378165/40753179-ba47f3e4-6427-11e8-9753-812db5454482.png)

But there's no way to go back and correct the issue.
First of all you can't upload the "fixed" package, because it already exists:
![image](https://user-images.githubusercontent.com/1378165/40753103-5f5948fc-6427-11e8-8a40-f18e935fafb8.png)

Second there's no option to delete the package, only unlist it:
![image](https://user-images.githubusercontent.com/1378165/40753154-91b4f620-6427-11e8-8913-a75f0afbc323.png)

Your only option is to increment the version number.

**Comment by anangaur** [comment] 2018-05-31 20:54
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4678

**Closed by anangaur** 2018-05-31 20:54 UTC
Labels: ClosedAs - Duplicate
