### ISSUE TITLE
Incorrect message when uploading a package with same version but different metadata

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#3920] opened 2017-05-09 20:46 UTC
Scenario:
1. A package with version 2.0.9+gitaa was already uploaded.
2. A new version with version 2.0.9+gitbb tries to upload.

The attached message is displayed. 
This is incorrect because the new package has the version 2.0.9+gitbb 
[NBBLib2bb.zip](https://github.com/NuGet/NuGetGallery/files/987963/NBBLib2bb.zip)

![message](https://cloud.githubusercontent.com/assets/16580006/25871826/9e6f4aea-34bd-11e7-9221-a6a2de40a99a.PNG)

**Comment by xavierdecoster** [comment] 2017-05-16 12:43
Looks like a duplicate of #3910, please check PR #3970

**Closed by xavierdecoster** 2017-05-16 12:43 UTC
Labels: Pillar: Experience
