### ISSUE TITLE
Assess whether or not the error message given to clients when they have surpassed the 250MB upload limit is useful

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5069] opened 2017-11-27 20:33 UTC
A customer trying to upload a 332MB nupkg was getting timeouts and not a useful error code.

Do all customers trying to upload a file >250MB get a timeout? If not, is the message they receive useful?

**Comment by skofman1** [comment] 2017-12-05 04:56
This is a duplicate of: https://github.com/NuGet/NuGetGallery/issues/4833

**Closed by skofman1** 2017-12-05 04:56 UTC
