### ISSUE TITLE
[GitHub Usage] Top dependent not showing

### ISSUE THREAD

**Issue by eerhardt** [NuGet/NuGetGallery#7379] opened 2019-07-26 16:05 UTC
### Describe the bug
A top dependent usage on github is not appearing for https://www.nuget.org/packages/System.Numerics.Tensors/0.1.0.

### To Reproduce
1. On this URL https://www.nuget.org/packages/System.Numerics.Tensors/0.1.0
2. Open GitHub Usage section
3. See that https://github.com/microsoft/onnxruntime is not listed in the list. Although it has 961 stars, 1k commits, and 81 contributors.

### Expected behavior
I expected OnnxRuntime to be listed in this section.

### Screenshots
![image](https://user-images.githubusercontent.com/8291187/61965137-2529e000-af95-11e9-862a-215cf1437084.png)

#### Here is where the dependency is:
https://github.com/microsoft/onnxruntime/blob/master/csharp/src/Microsoft.ML.OnnxRuntime/Microsoft.ML.OnnxRuntime.csproj#L150

You can also see it at: https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/

**Comment by loic-sharma** [comment] 2019-07-26 17:36
Thanks for reporting this! Right now, we only index repositories that are primarily C# for performance reasons. It looks like https://github.com/microsoft/onnxruntime is primarily a C++ repository, which is why it was skipped.

**Comment by skofman1** [comment] 2019-07-31 17:48
Unfortunately this is a known issue.. Closing as duplicate of https://github.com/NuGet/NuGetGallery/issues/7355

**Closed by skofman1** 2019-07-31 17:48 UTC
