### ISSUE TITLE
owner of package not visible in search

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#3364] opened 2016-11-21 19:38 UTC
There seems to be a window of time for which the package owner does not appear on the search.

![image](https://cloud.githubusercontent.com/assets/10507120/20497658/e2e2eeac-afde-11e6-83c2-d8f9d5049534.png)

**Comment by scottbommarito** [comment] 2016-11-21 19:42
When did you take that screenshot and what did you search for? I just searched for both "DataGen" and "karolhabczyk" and I was able to see the author.

**Comment by joelverhagen** [comment] 2016-11-21 20:07
I think it's a short window of time. My theory is:

1. Package gets uploaded to gallery
1. Feed to catalog consumes the new package
1. Catalog to lucene adds the package to the lucene index
1. Search service loads the index, merging in current owners.json
1. (some window of time goes by)
1. The owners.json file is updated and the owner of the uploaded package is added.
1. Search service loads the index, merging in current owners.json

During step 5 and 6, the package will appear in the search service but will have no owner. Note that this can only happen when a new package ID is introduced, meaning that ID will not be in owners.json.

One possible fix is to have the initial owner set in feed to catalog and owners.json will take care of ownership changes.

**Comment by joelverhagen** [comment] 2016-11-21 20:23
Looks like the owners.json job runs once per day, so we are looking at potentially 1 day of a package missing an owner in the search service.

Another fix would be to have the catalog to lucene job fetch the owner of packages not in owners.json and add it to the Lucene document. Then, update the search service to prefer owners in owners.json and fall back to the Lucene owner field.

**Comment by skofman1** [comment] 2016-11-28 23:56
Owners.json is updated once a day. This is by design.

**Comment by joelverhagen** [comment] 2016-11-29 01:03
Being updated once per day and showing a null owner are two different things. Job frequency can stay the same while still showing a good value.

**Comment by bchavez** [comment] 2018-04-04 16:24
I also ran into this issue with a newly published package. Showing a "null value" for the owner in search results made me initially think something was wrong with my `.nuspec` or **NuGet** package. Also made me think that I possibly had a run-away package. Had to double check to make sure I was still the owner in my profile. Glad to know it wasn't my fault. :sunglasses: 

![chrome_1435](https://user-images.githubusercontent.com/478118/38320277-fc4ffcac-37e8-11e8-8fbe-fd3ea77191f4.png)

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Comment by skofman1** [comment] 2018-04-04 16:32
@bchavez , any ideas for how to make the UI less confusing when the owner is unknown? Perhaps omitting the "by:"?

**Comment by bchavez** [comment] 2018-04-04 17:06
Hi @skofman1, hope you're doing really well. :sunglasses:  

For sure, omitting the "by:" would be a great start.

Some other cool ideas:

* If you have a `bool` you can check for a very first release, maybe keep around that **"This package isn't indexed in search yet."** warning that comes up when publishing new packages. No harm in keeping that message up for 24 hours for super-new packages? Especially, if that `bool` can append some extra wording that says, "If your package namespace is new, owner information won't be fully indexed until 24 hours."

* An entirely separate warning about owner info (and other things that might be related to super-new packages) that sticks around for 24h would work too.

:briefcase: :necktie: ***["Taking care of business every day... Taking care of business every way..."](https://www.youtube.com/watch?v=mmwic9kFx2c)***

**Comment by skofman1** [comment] 2018-08-22 23:34
We omitted the "by: " when fixing the issue here: https://github.com/NuGet/NuGetGallery/issues/6136 
Should be less confusing now. 
Closing this issue. Feel free to reopen if you think this fix is insufficient.

**Closed by skofman1** 2018-08-22 23:34 UTC
Labels: Area: Search, Priority - 3, Type:Bug
