### ISSUE TITLE
[A11y][WCAG2.1]Some of the contents of API Key page get overlapped when screen is zoom to 400%.

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#8281] opened 2020-10-19 19:29 UTC
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1061307
​
Environment Details:
Application Name: NuGet Service
Application URL:https://www.nuget.org/
Windows Version - Windows10 
Edge Version-Microsoft Edge 44.18362.449.0
Chrome Version- Version 79.0.3945.130 (Official Build) (64-bit)

Pre-requisite:
Set the desktop size value to 1280 x 1024.

Note:
Same issue is observed in Upload packages page

Steps to Reproduce :
1.Launch application using provided URL.(https://www.nuget.org/)
2.Navigated to Home page
3.Click on “Sign in” option (top right) and click on “Sign in with Microsoft” button
4.Sign in using MSA on the common Microsoft sign-in page
5.Go to “API Keys” from the context menu (top left menu dropdown).
6.Navigate till "Create Control" and expand it.
7.Observe that some of the contents get overlapped when the screen is zoom to 400%.

Actual: 
When the screen is zoomed to 400%,  Some of the contents present on the screen get overlapped.
The below data shown in the screenshot gets overlapped after zooming the screen :
Image

Expected: 
When screen is zoomed to 400%, all the contents present on the screen should not get overlapped and should appear properly on the screen.

User Impact: 
Low vision users will find difficulty in viewing and reading the content present on the screen when zoomed to 400%.

Notes:
See this screenshot:
![image](https://user-images.githubusercontent.com/11051729/96502433-a0188f80-1206-11eb-89ea-6097e412051e.png)

**Comment by agr** [comment] 2020-10-19 22:45
Duplicate of https://github.com/NuGet/NuGetGallery/issues/8190

**Closed by agr** 2020-10-19 22:45 UTC
Labels: Area: Accessibility
