### ISSUE TITLE
add ability to exclude "net runtime" packages

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/NuGetGallery#4530] opened 2017-08-09 01:45 UTC
https://preview.nuget.org/stats

the package download stats have been seriously skewed with the introduction of .net core/standard. basically moving forward every non "runtime package" will have a dependency on several "runtime packages". so eventually the entire list of top download will be "what used to be installed as part of the .net runtime". I don't think that is the aim of this table

![image](https://user-images.githubusercontent.com/122666/29101792-f59cca22-7cf7-11e7-8eeb-4b5c9088a355.png)

**Comment by maartenba** [comment] 2017-08-09 06:46
#3417

**Comment by joelverhagen** [comment] 2017-08-09 13:46
Thanks -- indeed a duplicate of https://github.com/NuGet/NuGetGallery/issues/3417.

**Closed by joelverhagen** 2017-08-09 13:46 UTC
Labels: ClosedAs - Duplicate
