### ISSUE TITLE
[Redesign] Favicon needs the new icon

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4370] opened 2017-07-11 18:23 UTC
![image](https://user-images.githubusercontent.com/14800916/28083774-6a294160-662b-11e7-9c7d-c8188dcc1f92.png)

**Comment by joelverhagen** [comment] 2017-07-11 22:34
Already addressed, not yet deployed.

Duplicate of https://github.com/NuGet/NuGetGallery/issues/4345.

**Closed by joelverhagen** 2017-07-11 22:34 UTC
Labels: ClosedAs - Duplicate
