### ISSUE TITLE
Review V3 monitoring

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2626] opened 2015-08-18 10:28 UTC
Review V3 monitoring & find missing items.

@bhuvak @johnataylor

**Comment by yishaigalatzer** [comment] 2016-10-20 00:55
This is a duplicate of https://github.com/NuGet/NuGetGallery/issues/3067 and similar issues. Closing

**Closed by yishaigalatzer** 2016-10-20 00:55 UTC
Labels: Area: Monitoring & Alerting
