### ISSUE TITLE
Support AAD authentication on NuGet.org

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4205] opened 2017-06-15 17:35 UTC
Based on current Microsoft ID recommendations:

> It is highly recommended that all new services from Microsoft integrated with both Azure AD (work/school accounts) and MSA (personal accounts).

Right now, AAD only is used when admins log in.

**Comment by skofman1** [comment] 2017-06-15 18:42
Sounds the same as the planned 2FA work.
@shishirx34 , can we close as duplicate?

**Comment by shishirx34** [comment] 2017-06-15 19:27
Yes duplicate of 2FA work.

**Comment by joelverhagen** [comment] 2017-06-15 19:28
What the duplicate issue?

**Closed** 2017-06-15 19:27 UTC

**Comment by shishirx34** [comment] 2017-06-15 19:30
https://github.com/NuGet/NuGetGallery/issues/3252
