### ISSUE TITLE
Documentation block on the package info page doesn't display markdown correctly until you click "show more"

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/NuGetGallery#4784] opened 2017-10-01 01:12 UTC
The gallery's rendering of the short version of the "documentation" block and the expanded section are not the same. The short version does not render markdown correctly. Clicking the "show more" link expands the block and renders the markdown correctly.

# Repro
1. Edit a package. E.g. https://www.nuget.org/packages/Yarn.MSBuild/1.0.1/Edit
1. Add this URL to the "Import Readme" => "URL" box: https://raw.githubusercontent.com/natemcmaster/Yarn.MSBuild/v1.0.1/README.md. This file contains this section

# Expected result

The "Documentation" section of https://www.nuget.org/packages/Yarn.MSBuild/1.0.1 shows the first paragraph or two from my README file

# Actual result

See https://www.nuget.org/packages/Yarn.MSBuild/1.0.1

The page shows what is normally "invisible" markdown, aka, markdown links. 

## Before clicking "Show more"
![image](https://user-images.githubusercontent.com/2696087/31050784-a6b3a9bc-a60a-11e7-8eaa-59985c6e1667.png)

## After clicking "Show more"

![image](https://user-images.githubusercontent.com/2696087/31050787-c5f8f1a6-a60a-11e7-9bd9-130bd8a8106d.png)

**Comment by anangaur** [comment] 2017-10-01 01:47
Dupe of https://github.com/NuGet/NuGetGallery/issues/4770

**Comment by chenriksson** [comment] 2017-10-16 15:33
Closing, will track with #4770

**Closed by chenriksson** 2017-10-16 15:33 UTC
