### ISSUE TITLE
multiple versions shown as Latest

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2598] opened 2015-07-29 21:24 UTC
When multiple versions of a package are uploaded in parallel, there is a probability of multiple version being updated in DB at the same time causing IsLatest to be set to true on both of them.

https://www.nuget.org/packages/System.Runtime/

**Comment by maartenba** [comment] 2015-07-30 12:14
Manually fixed these occurences in database. @bhuvak can you check catalog/search?

We'll discuss a fix for this via email.

**Comment by maartenba** [comment] 2015-08-18 10:17
Closing - duplicate of #2514

**Closed by maartenba** 2015-08-18 10:17 UTC
