### ISSUE TITLE
Nuget.org search results are not based on 'popularity'

### ISSUE THREAD

**Issue by jainaashish** [NuGet/NuGetGallery#5332] opened 2018-01-23 02:50 UTC
From VSFeedback - 554126

Search for 'pinvoke' on nuget.org
it will give you packages in random order where packages with as low as 120 downloads are in top list.

Now, search for 'pinvoke author:andrew',
it will give andrew arnott's pinvoke libraries which has hundreds of thousands downloads. 
Should first search query not have listed these packages in top list?

**Comment by skofman1** [comment] 2018-08-29 17:32
This is a known issue caused by this bug: https://github.com/NuGet/NuGetGallery/issues/3778

Closing as duplicate.

**Closed by skofman1** 2018-08-29 17:32 UTC
Labels: Area: Search
