### ISSUE TITLE
Have better UI to unlist all package versions at once

### ISSUE THREAD

**Issue by nkolev92** [NuGet/NuGetGallery#5534] opened 2018-02-22 20:45 UTC
@rohit21agrawal commented on [Wed Aug 10 2016](https://github.com/NuGet/Home/issues/3295)

There should be a way to unlist all packages/package versions instead of having to go separately on each version and un-listing.

---

@rrelyea commented on [Fri Aug 19 2016](https://github.com/NuGet/Home/issues/3295#issuecomment-241057487)

Rohit had a support request for a customer that had many things to unlist.
We ended up helping him write a script, but our server UI should be enhanced to support this better.

---

@rohit21agrawal commented on [Fri Aug 19 2016](https://github.com/NuGet/Home/issues/3295#issuecomment-241058137)

Current workaround for doing this through a script :

Powershell : 

```
$apiKey = "[fill in API key here]"


$packageList = @() # fill in package list array

# foreach package, get the project.json and get the versions foreach($package in $packageList) {
    $lower = $package.ToLowerInvariant();

    $json = Invoke-WebRequest -Uri "https://api.nuget.org/v3-flatcontainer/$lower/index.json" | ConvertFrom-Json

    foreach($version in $json.versions)
    {
      Write-Host "Unlisting $Package, Ver $version"
      nuget delete $package $version $apiKey -source https://api.nuget.org/v3/index.json
    }
}
```

Ruby : https://gist.github.com/haf/760ac442e309b94bd891656444ef5615

---

@aloneguid commented on [Tue Mar 28 2017](https://github.com/NuGet/Home/issues/3295#issuecomment-289713930)

@rohit21agrawal this is brilliant, thank you. A small modification to this and ready to use function for your profile:

```powershell
function Remove-AllNuGetPackageVersions($PackageId, $ApiKey)
{
    $lower = $PackageId.ToLowerInvariant();

    $json = Invoke-WebRequest -Uri "https://api.nuget.org/v3-flatcontainer/$lower/index.json" | ConvertFrom-Json

    foreach($version in $json.versions)
    {
      Write-Host "Unlisting $PackageId, Ver $version"
      Invoke-Expression "nuget delete $PackageId $version $ApiKey -source https://api.nuget.org/v3/index.json -NonInteractive"
    }
}
```

---

@PatoBeltran commented on [Thu Feb 22 2018](https://github.com/NuGet/Home/issues/3295#issuecomment-367809009)

@joelverhagen can you take a look at this and see if this is still a relevant concern?

---

@rohit21agrawal commented on [Thu Feb 22 2018](https://github.com/NuGet/Home/issues/3295#issuecomment-367811614)

This should be moved to NuGet gallery

**Comment by skofman1** [comment] 2018-03-15 22:39
This is a duplicate of : https://github.com/NuGet/NuGetGallery/issues/367 
The reason we don't have this UI is because V3 indexing pipeline is slow in handling updates to registrations with multiple versions, so it can cause delays for all users.

**Closed by skofman1** 2018-03-15 22:39 UTC
