### ISSUE TITLE
Can't install profile 238 nuget package into Xamarin.iOS project using Nuget 3.0

### ISSUE THREAD

**Issue by jherby2k** [NuGet/NuGetGallery#2473] opened 2015-05-10 18:32 UTC
Newtonsoft.Json for example fails to install in Xamarin.iOS using VS2015 RC, but works fine in Visual Studio 2013. The error is:

Could not install package 'Newtonsoft.Json 6.0.8'. You are trying to install this package into a project that targets 'Xamarin.iOS, Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Newtonsoft.Json is a PCL profile 328 package, which should support Xamarin.iOS.

This means no one can use Azure Mobile (which depends on JSON.NET) in Xamarin iOS, under Visual Studio 2015.

**Comment by emgarten** [comment] 2015-05-13 20:49
Duplicate of https://github.com/NuGet/Home/issues/562

**Closed by emgarten** 2015-05-13 20:49 UTC
