### ISSUE TITLE
[Feature]: Dark mode for NuGet.org!

### ISSUE THREAD

**Issue by jcjiang** [NuGet/NuGetGallery#8820] opened 2021-09-22 22:12 UTC
### The Elevator Pitch

No need to worry about blinding yourself at 2 AM in the morning when you are searching for quality packages on NuGet.org. With Dark Mode for NuGet.org turned on, all pages will have a dark background. There will also sufficient contrast with the content on a page so you will still be able to access everything you need. 

Examples:

![image](https://user-images.githubusercontent.com/23298667/134428906-3b26e4d3-19be-4266-ae6b-63f8666ac0a8.png)

![image](https://user-images.githubusercontent.com/23298667/134428938-f847c5b0-bfd3-4336-a61b-723226a87faa.png)

**Comment by augustoproiete** [comment] 2021-09-22 23:46
Looks like this might be a duplicate of https://github.com/NuGet/NuGetGallery/issues/8773

**Comment by jcjiang** [comment] 2021-09-23 00:21
Oops - was on vacation and my brain buried everything that came before.
Thank you so much for the catch!

**Closed** 2021-09-23 21:36 UTC
Labels: feature-request
