### ISSUE TITLE
Include package size in search and registrations

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2957] opened 2016-03-23 08:24 UTC
Include package size in search and registrations, see https://github.com/NuGet/Home/issues/2375#issuecomment-200081479

Are there other fields we may want to add?

**Comment by maartenba** [comment] 2016-03-23 08:24
(adding @yishaigalatzer as CC)

**Comment by jhaamit6666** [comment] 2016-03-23 08:59
Owners of the package and link to [Package Statistics](https://www.nuget.org/stats/packages/NLog?groupby=Version&groupby=ClientName&groupby=ClientVersion&groupby=Operation) as marked in the snapshot. 
![1](https://cloud.githubusercontent.com/assets/16834561/13980256/933dcb82-f103-11e5-8790-8d67c6fcb76f.png)

**Comment by 304NotModified** [comment] 2016-05-18 21:44
I would find "has strong name" (maybe including version) be useful. Strong naming is still needed these days and lead to unclear errors.

**Comment by jhaamit6666** [comment] 2016-05-19 09:31
kindly close this issue if solution found or to be implemented or "won't fix".

**Comment by skofman1** [comment] 2017-12-05 21:55
Having the size on Gallery as well will be useful.

**Comment by onovotny** [comment] 2018-02-13 01:02
Any updates there? Agree that size would be useful

**Comment by skofman1** [comment] 2018-02-13 21:15
@onovotny , the team is working on other areas in the moment, and since exposing the package size in 
 V3 is a lot of work, it is not work planned for the near future. 
However, exposing the package size on the Gallery is quite easy, and I created a separate issue for that: https://github.com/NuGet/NuGetGallery/issues/5471

**Comment by anangaur** [comment] 2019-04-16 21:21
Closing this as a duplicate of https://github.com/NuGet/Home/issues/7957. There are bunch of metadata that needs to be shown on the VS PM UI.

**Comment by anangaur** [comment] 2019-04-16 21:21
The Gallery already shows the size information (implemented as part of #5471).

**Closed by anangaur** 2019-04-16 21:21 UTC
Labels: Type:Feature
