### ISSUE TITLE
[NuGet.org Bug]: XML Comments in Code Block not rendered in nuget.org

### ISSUE THREAD

**Issue by kepboy** [NuGet/NuGetGallery#10230] opened 2024-10-18 07:11 UTC
### Impact

It bothers me. A fix would be nice

### Describe the bug

I have created several pacakges, and for those packages I have created README.md files. Those markdown files contain XML code blocks. Within those code blocks I have added XML comments to remove irrelevant content (so I can focus the reader on the releavent stuff). However, when I publish those packages, the README content that is rendered on nuget.org does not show those XML comments (presumably because they are also HTML comments).

You can see an example of the behaviour here, in this package
* https://www.nuget.org/packages/PlayNicely.Projects/1.1.3-beta-550#example

Yet, when rendered in gitlab, it works as expected
* https://gitlab.com/play-nicely/foundation/-/tree/main/Code/PlayNicely.Projects/PN.Projects?ref_type=heads#example

### Repro Steps

1. Create a package with a README.md file.
2. Add a code block to the readme file, ```xml
3. Add an XML comment to the code block
4. Publish the package
5. 

### Expected Behavior

The comment should be rendered correctly.

### Screenshots

![readme-good](https://github.com/user-attachments/assets/97028afd-9f60-46aa-81d5-de074f66e0b8)
![README-bad](https://github.com/user-attachments/assets/c466e68c-214d-459b-8c1a-a79b2ccbe4bd)

**Comment by joelverhagen** [comment] 2024-10-18 12:46
This is a duplicate of https://github.com/NuGet/NuGetGallery/issues/9060.
Expanded the title of the other issue to include XML so it's more clear.

**Closed by joelverhagen** 2024-10-18 12:46 UTC
Labels: Type:Bug
