### ISSUE TITLE
Send Notifications when an Owner is removed from a package

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#385] opened 2012-01-13 00:05 UTC
Related to: https://github.com/NuGet/NuGetGallery/commit/14ba5852a60d92bb1285d30d322855927c099866#commitcomment-863005

When an owner is removed from a package, we should notify that owner using a format similar to "Your password was just changed, was this you?" emails services often use.

**Comment by xavierdecoster** [comment] 2015-05-26 11:49
The `JsonApiController` is [throwing](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/JsonApiController.cs#L101) if the request to remove a package owner does not originate from the package owner.

@csharpfritz:
As a user who no longer wants to be a package owner, do you want to receive an email notification of this operation? (very easy)

If not, can admins currently change package ownership? If that's the case, this issue should be updated and triaged as an operations-issue (admin operation should trigger the notifications then). If that's not the case and we don't want this, we can close the issue.

**Comment by csharpfritz** [comment] 2015-05-26 14:20
I think the owner that is removed should be notified with a link or email
address to contact if the operation was in error.

Admins can change ownership, and I think that change should trigger the
notification as well.



Jeff

**Comment by maartenba** [comment] 2015-09-08 06:18
Dupe of https://github.com/NuGet/NuGetGallery/issues/1844

**Closed** 2016-12-30 19:23 UTC
Labels: Priority - 2
