### ISSUE TITLE
Nuget.Server slow when rebuilding cache (after-during push)

### ISSUE THREAD

**Issue by ikalafat** [NuGet/NuGetGallery#6960] opened 2019-03-05 21:57 UTC
Backstory:

- We have Nuget.Server (v3.1.2) running on VM (8CPU/8GB, Windows Server 2012R2). 
- Nuget.Server files are located in C:\inetpub\.. folder, while actual Nuget packages are stored on D drive. 
- Nuget.Server is running within dedicated Application pool, using NetworkService Identity.
- `enableFileSystemMonitoring` is set to `true`
- currently we have around 54k files in whole repository (.nupkg, nuspec and sha files included), around of 3GB total size. 
- cache file is around 24MB
- every couple of months, we cleanup obsolete packages to reduce overall repository/cache size. That helps, but not for long

Problem:
- we are pushing nugets on a daily basis (depending on solution/related project) to that server (6-10 nupkg files). 
- nupkgs are pushed sequentially (one by one)
- after 3-4 nupkgs being pushed very fast (lets say 5-10 seconds), rebuilding the cache kicks in here (file is cleared, is 1kb in size), causing very next nupkg to be pushed extremely slow (45-60s) in respect to others until the cache is rebuilt. 
- this gets worse if it happens that two or more people pushes nugets at the same time. 

Question:
- is there way to circumvent this slowness? For example, is there a way to "delay" cache rebuilding after some quiet time (such as 30 seconds since last push?)
- any other ideas to improve performances are welcome

Thanks.

**Comment by loic-sharma** [comment] 2019-03-06 17:19
It sounds like the cache is being rebuilt when it shouldn't. From my understanding, these things cause a cache rebuild:

1. If the cache is empty
2. On initialization of the package repository
3. Once an hour the cache is rebuilt
4. On certain file system events

If my understanding is correct, none of these explain why your cache is rebuilt after pushing packages. I'm wondering if this is a concurrency issue. It seems that the file system events are ignored during package pushes by setting a `_isFileSystemWatcherSuppressed` flag, however this flag is released after the file system's lock is released (see [this code](https://github.com/NuGet/NuGet.Server/blob/2ee751ab71048d87f97f45807a420517a9aa9e27/src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs#L714)). This seems like a bug:

1. Request 1 uploads a package, acquires the file system lock, and sets the `_isFileSystemWatcherSuppressed` flag
2. Request 2 uploads a package and waits on the file system lock
3. Request 1 finishes the upload and releases the file system lock. The `_isFileSystemWatcherSuppressed` flag is enabled, so the file system watcher does nothing
4. Request 2 acquires the file system lock and sets the `_isFileSystemWatcherSuppressed` flag
5. Request 1 unsets the `_isFileSystemWatcherSuppressed` flag
6. Request 2 finishes the upload. The `_isFileSystemWatcherSuppressed` flag is disabled, so the file system watcher sees the new package and initiates a cache rebuild

It seems that we should unset the `_isFileSystemWatcherSuppressed` flag before releasing the file system lock. Does that sound right @joelverhagen ?

**Comment by joelverhagen** [comment] 2019-03-06 17:45
Yup, that seems right. 

We should be able to simulate this in an integration test.

**Comment by joelverhagen** [comment] 2019-03-06 17:46
Also, it should be very easy to make a `dev` build with this fix, put it on MyGet, and let @ikalafat try the fix out.

**Comment by joelverhagen** [comment] 2019-03-06 18:21
@ikalafat, I have made this small change. Could you try this pre-release build of NuGet.Server and tell me if it mitigates the issue?

It's on our pre-release MyGet feed:
https://dotnet.myget.org/F/nuget-build/api/v3/index.json

Package ID: NuGet.Server
Version: 3.1.3-jver-6960-2470822

**Comment by ikalafat** [comment] 2019-03-06 22:35
@joelverhagen and @loic-sharma 

Thanks for quick response on this one. 

I've pulled this build that you have pushed and copied the files to server. 

I'll monitor performance in next day or two, and ask other colleagues to do the same - I'll let you know if there are improvements.

**Comment by joelverhagen** [comment] 2019-03-06 23:02
Sounds good. The change I gave you may not be enough. I fixed that one problem but ran into another, trickier problem caused by late file system events. I've fixed that issue as well. Can you take this newer version and give it a spin?

Version: 3.1.3-jver-6960-2472574

**Comment by ikalafat** [comment] 2019-03-06 23:03
Sure, no problem. Thanks!

**Comment by ikalafat** [comment] 2019-03-08 11:19
Hey @joelverhagen, 

I haven't noticed such delays anymore, nor the colleagues mentioned that it is happening again. 

However, give us a couple of more days to verify, just to be sure. 

Thanks.

**Comment by joelverhagen** [comment] 2019-03-08 16:24
Glad to hear things got better. I would like to merge this change by the end of next week (March 15, 2019). Do you think you could get back to me by then with this final verification? If you've seen no more problems in that time I think it's safe to say we have at least _improved_ the situation and a new NuGet.Server release should be made with this change.

**Comment by ikalafat** [comment] 2019-03-11 10:05
Hi @joelverhagen lets get this baby merged! 

Pretty much similar comment as before -  I'm not seeing these delays anymore. 

Thanks so much for quick fix.

**Comment by joelverhagen** [comment] 2019-03-11 20:53
Merged and shipped 😄.

https://www.nuget.org/packages/NuGet.Server/3.2.0

**Closed by joelverhagen** 2019-03-11 20:53 UTC
Labels: Area: NuGet.Server, Customer Issue
