### ISSUE TITLE
Implement RetryAfter for flaky validators (VCS cough cough)

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4650] opened 2017-09-11 18:41 UTC
1. Handle cases where multiple validation results come back (what if one is good and one is bad?)
1. Add configuration
1. Make sure RetryAfter < FailAfter

**Comment by skofman1** [comment] 2018-08-23 22:48
Closing since VCS is deprecated and the issue is not specific.

**Closed by skofman1** 2018-08-23 22:48 UTC
Labels: Priority - 3
