### ISSUE TITLE
[NuGet.org Bug]: Download statistics are not updated

### ISSUE THREAD

**Issue by mariuszgromada** [NuGet/NuGetGallery#9352] opened 2023-01-17 15:49 UTC
### Impact

I'm unable to use NuGet.org statistics

### Describe the bug

For many days now, for some packages, the download statistics show the same value. 

![image](https://user-images.githubusercontent.com/16277367/212944506-2c434a9c-0cbf-4d2c-8b4c-55a65654583e.png)

Confirmation can also be found in Nuget Trends.

![image](https://user-images.githubusercontent.com/16277367/212944848-ddf90b75-f300-4598-8d51-8c7b79a11faa.png)

### Repro Steps

On this URL: https://www.nuget.org/packages?q=math
On this URL: https://nugettrends.com/packages?months=24&ids=MathParser.org-mXparser

### Expected Behavior

MathParser.org-mXparser package has c.a. 1500-2000 downloads daily.

**Comment by agr** [comment] 2023-01-18 00:43
Investigating. Our statistics pipeline reports 1,324,021 downloads for that package, but apparently it is not propagated to the rest of the system.

**Comment by agr** [comment] 2023-01-18 01:36
Actually, this number is also reported by the search service: https://azuresearch-usnc.nuget.org/query?q=MathParser.org-mXparser

![image](https://user-images.githubusercontent.com/102933/213058777-86916bef-0d8b-40cd-b751-18bb2d865ea8.png)
And, as far as I understand, the search service is the data source for nugettrends. So, regarding why data is missing there, you'd probably have to ask [nuget-trends folks](https://github.com/dotnet/nuget-trends).

Still looking why Gallery number is off.

**Comment by agr** [comment] 2023-01-23 21:47
I'm still looking into the issue. Something seems to be wrong with our statistics ingestion into Gallery. I am preparing a change that adds more telemetry, that hopefully would help understanding what's going on. It will take a few days to roll out.

**Comment by mariuszgromada** [comment] 2023-01-24 19:42
Strange, now API shows again less
![image](https://user-images.githubusercontent.com/16277367/214392420-d5ad41f5-776c-486e-b98b-acf6455a0057.png)

**Comment by agr** [comment] 2023-01-26 01:20
Regarding the search service numbers: I think we found the cause of it and applied a mitigation. We'll need to wait for some time for the statistics data to get reingested into the search.
/cc @advay26

**Comment by agr** [comment] 2023-02-03 01:27
We deployed the Gallery with extra telemetry for this case, and the issue seem to have stopped reproducing. I'll keep an eye on the download counts in the next few days.

**Comment by agr** [comment] 2023-02-07 00:04
Download counts still seem to be in sync between Gallery and the search service. I'll close the issue for now as we lost repro. Feel free to reopen if it happens again and we'll have more telemetry that hopefully would let us understand what's going on.

**Closed by agr** 2023-02-07 00:04 UTC
Labels: Type:Bug
