### ISSUE TITLE
NuGet Server cannot find (and doesn't list in the feed) some newly pushed packages

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3967] opened 2017-05-15 20:34 UTC
@caioproiete commented on [Wed May 10 2017](https://github.com/NuGet/Home/issues/5209)

I'm using the latest NuGet Server released as of now (v2.11.3) to host my company's NuGet feed, and after pushing new packages to the server via nuget push, although the packages are being received and stored correctly in the nuget packages folder in the server, they are not being listed in the feed when using Visual Studio (Browse) and trying to install specific versions via NuGet Console also won't work (as it cannot find the packages).

The only way I can get newly published packages to appear, is by manually deleting the file `serverName.cache.bin` from the packages folder in the server, followed by an `iisreset`, which suggests the index is not being properly updated as new packages are published.

---

NuGet Server v2.11.3
Visual Studio 2017
Hosting on Windows Server 2012, IIS, .NET 4.6.2

**Comment by skofman1** [comment] 2017-05-15 20:34
@joelverhagen ?

**Comment by joelverhagen** [comment] 2017-05-16 13:51
Hey @caioproiete, this sounds like an issue that was fixed a while back by 2.11.3: https://github.com/NuGet/NuGetGallery/issues/3277

Have you been able to see a pattern in when this issue reproduces?

Have you tried an older version of NuGet.Server to see if the issue gets better or worse?

Do you have some consistent repro steps for this?

Could you describe in detail how do you deploy your web app?

**Comment by joelverhagen** [comment] 2017-06-07 00:55
Closing. @caioproiete, feel free to re-open if you keep running into this issue.

**Comment by rducom** [comment] 2018-08-29 15:29
Just ran into this issue.
When we push, the server responds 200 (Your package was pushed.), but it's not indexed.
The only fix is to delete all the release of the same nuget name.
Then push again......

I have kept all the releases of the related package if you ever want to try to reproduce.
Issue happen on version 3.1.2.0

**Comment by MarkKharitonov** [comment] 2019-01-25 17:06
Same here. Does not show the newly pushed packages.

**Comment by MarkKharitonov** [comment] 2019-01-25 17:06
I am using 3.1.2.0 as well.

**Comment by joelverhagen** [comment] 2019-01-25 17:08
Thanks for bringing this to our attention again. Could you provide a minimal repro from a new web project? Last time I investigated this issue I tried a lot of variations and could not reproduce the issue.

**Comment by MarkKharitonov** [comment] 2019-01-25 19:12
Do you think we could have a short zoom session? I will show you.

**Comment by joelverhagen** [comment] 2019-01-25 20:52
@MarkKharitonov, I am busy this whole afternoon. Reach out to me jver [at] microsoft.com and we'll try to coordinate a time for next week.

**Comment by MarkKharitonov** [comment] 2019-01-26 05:55
I reached to the conclusion that NuGet.Server does not expose nuget packages where the version field in the nuspec contains the commit Id, like `1.0.19007.4+f26968b`

**Comment by joelverhagen** [comment] 2019-01-26 07:57
This is a SemVer 2.0.0 version string which are hidden by default. See:
https://github.com/NuGet/Home/wiki/Semver-2.0.0-Protocol

In short, you need to specify `semVerLevel=2.0.0` as a query parameter. This is what NuGet client version release in the past year and a half have done.

**Comment by joelverhagen** [comment] 2019-01-26 18:19
The reason is not default is because older clients (2.8.6, for example) do not support SemVer 2.0.0 versions. This means that if they encounter such a version they throw an exception making that package or page or results unusable. All 3.x clients support SemVer 2.0.0 but only until NuGet 3.5 and later supports the protocol of appending `semVerLevel=2.0.0` to the query string.

Currently there is not NuGet.Server feature to show SemVer 2.0.0 by default. What client are you using to read the feed?

If it would be helpful to you, please consider making a pull request to NuGet.Server. You could add something to the configuration (off by default) and disable the SemVer 2.0.0 filtering in places like this (there are other places that need the change too, I think...):
https://github.com/NuGet/NuGet.Server/blob/fe2231b0373b9ecc3333a51695f8ec8864fc1368/src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs#L171-L174

**Comment by MarkKharitonov** [comment] 2019-01-27 04:49
I consume NuGet packages in 3 ways - nuget.exe, dotnet restore and Powershell Install-Package
The command line is:
```
Install-Package DevOpsAutomation -Source "http://devstatic/prdnuget/nuget?semVerLevel=2.0.0" -Force -Scope CurrentUser
```
It fails with:
```
Install-Package : No match was found for the specified search criteria and package name 'DevOpsAutomation'. Try Get-PackageSource to see all available registered package sources.
```
Attempting to install another package which uses semver 1 fails too unless I remove `?semVerLevel=2.0.0`, in which case it succeeds.

The package is not visible if I navigate to `http://devstatic/prdnuget/nuget/Packages` in the Internet Explorer, but it is visible with `http://devstatic/prdnuget/nuget/Packages?semVerLevel=2.0.0.0`, so I know it should work.

Seems like `Install-Package` fails with the query parameter.

**Comment by joelverhagen** [comment] 2019-01-30 18:39
I am closing this issue now. To avoid noise to the other people on this thread, please open a new issue if you run into this problem and have assessed that SemVer 2.0.0 filtering is not the reason, since this is by design.

Thanks!

**Closed by joelverhagen** 2019-01-30 18:39 UTC
Labels: Area: NuGet.Server
