### ISSUE TITLE
whitelist some packages for downloads count

### ISSUE THREAD

**Issue by zhili1208** [NuGet/NuGetGallery#3839] opened 2017-04-27 21:03 UTC
https://www.nuget.org/packages/XrmLibrary.EntityHelpers.2015/ 
https://www.nuget.org/packages/XrmLibrary.EntityHelpers.2016/
https://www.nuget.org/packages/XrmLibrary.ExtensionMethods/
https://www.nuget.org/packages/XrmLibrary.ExtensionMethods.2016/

https://github.com/NuGet/NuGetGallery/issues/3836

**Comment by shishirx34** [comment] 2017-04-27 21:08
XrmLibrary.ExtensionMethods download count seems fine. The rest of the packages need to be whitelisted in stats job I believe.

**Comment by emregulcan** [comment] 2017-04-27 21:19
hi @shishirix34,
i'm owner of these packages. XrmLibrary.ExtensionMethods counts sees right but actually not, because there are 2 different packages (XrmLibrary.ExtensionMethods and XrmLibrary.ExtensionMethods.2016) and count stats shows for v1 and v2016.1.0 and I think they are not right

**Comment by scottbommarito** [comment] 2017-04-27 21:29
Closed as duplicate of https://github.com/NuGet/NuGetGallery/issues/3836

**Closed by scottbommarito** 2017-04-27 21:29 UTC
