### ISSUE TITLE
Unable to load service index for api.nuget.org/v3/index.json

### ISSUE THREAD

**Issue by zhili1208** [NuGet/NuGetGallery#5680] opened 2018-03-23 22:40 UTC
@neo0000 Moved from https://github.com/NuGet/Home/issues/6728

this looks like a server issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 4.5.0.4685

dotnet.exe --version (if appropriate):

VS version (if appropriate): VS2017 version 15.5.6

OS version (i.e. win10 v1607 (14393.321)): win10 v1709

Worked before? If so, with which NuGet version: Worked before with same version: 4.5.0.4685

## Detailed repro steps so we can see the same problem

1. Accessing nuget.org via visual studio using NuGet Package Manager
2. Desktop is connected to the internet.
3. One item did appear from the list, which is Error occured from the NuGet Package Manager UI.
4. From the output window of VS2017 it says: 
[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.
An error occurred while sending the request.
  The remote server returned an error: (502) Bad Gateway.
5. Tried to access API url: https://api.nuget.org/v3/index.json from the browser, and this is what it return:
![nuget_error](https://user-images.githubusercontent.com/37679573/37808553-ec9a35be-2e85-11e8-8a83-edf1bef5bab5.PNG)
6. Also tried to access API url from a different network but the problem still persist.

Thanks.

**Comment by skofman1** [comment] 2018-04-02 18:01
@neo0000, apologies for the slow response. Are you still experiencing the issue?

**Comment by neo0000** [comment] 2018-04-05 01:57
Hi @skofman1 ,

Seems the problem is that the site is blocked in Hongkong(well I just found out today that we have an ISP here). The IT support team at the office tried to use a different ISP and it seems working well. I could access it using browser and Visual Studio NuGet manager.

**Comment by skofman1** [comment] 2018-04-05 02:29
Can you tell me the name of the ISP. We can work with our CDN provider to investigate.

**Comment by neo0000** [comment] 2018-04-05 02:38
Hi @skofman1 ,

Here is the ISP name: Telstra Hk

**Comment by shishirx34** [comment] 2018-04-05 23:35
@neo0000 - I am reaching out to our CDN provider, it will be helpful if you can get us MTR logs from the machine that isn't able to access the service index. Please follow the steps here: https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#nugetorg-not-accessible and send us the MTR log to support@nuget.org, include my handle in the email to route to me.

**Comment by neo0000** [comment] 2018-04-06 08:39
Hi @shishirx34 ,

I already send an email to support@nuget.org.

**Comment by shishirx34** [comment] 2018-04-06 23:08
Hi @neo0000 - we need some additional information for CDN, please find the below request

> It looks like the user's connection is not getting outside of his router possibly due to DNS resolution. If the user was to run the MTR to google.com or yahoo.com would he able to make a successful connection?
> Could he attempt to run an MTR to an IP instead such as the APAC VIP for NuGet, 117.18.232.200?

Could you try running MTR against the above IP address? Also, can you verify that your connections to other websites(google.com/yahoo.com) are fine from the same machine?

**Comment by shishirx34** [comment] 2018-04-11 19:18
Hi @neo0000 - I am still awaiting on the asks for the CDN. Is this not an issue anymore for you?

**Comment by neo0000** [comment] 2018-04-12 04:58
Hi @shishirx34 

I was been busy and sorry about that, kindly check the images. I used the MTR with an ISP from HK

![mtr_1](https://user-images.githubusercontent.com/37679573/38657124-188636de-3e51-11e8-981d-f0b619262ce7.PNG)

![mtr_2](https://user-images.githubusercontent.com/37679573/38657127-1b75535c-3e51-11e8-8f31-24938433d397.PNG)

![mtr_3](https://user-images.githubusercontent.com/37679573/38657128-1d4e0c96-3e51-11e8-9065-90b64631f23a.PNG)

**Comment by shishirx34** [comment] 2018-04-12 16:37
Thank you @neo0000. I have forwarded your findings to our CDN provider.

**Comment by neo0000** [comment] 2018-04-13 01:07
Welcome @shishirx34

**Comment by shishirx34** [comment] 2018-04-13 17:39
Hi @neo0000, we got an update from the CDN folks. And it looks like the issue could possibly be lying on your end. See the response below:

> I looked at the MTRs that you provided and I can see that we are blocked on that end.
> As David(previous contact for CDN) had mentioned, it looks like the user's connection is not getting outside of his router possibly due to DNS resolution.
> He can also check with his ISP to see if they are blocking us.
> Last but not least, can you please provide the customer’s public IP address so we can also run MTRs from us to them?

I understand this is not really ideal, but do you mind mailing me the public IP address for your machine that faces this issue. You can email us on support@nuget.org if you are uncomfortable sharing the IP here. Also, can you check with your ISP, if possible, that they are somehow blocking nuget.org(CDN)

**Comment by shishirx34** [comment] 2018-04-16 16:55
@neo0000 - just following up, is this still an issue?

**Comment by neo0000** [comment] 2018-04-17 01:43
Hi @shishirx34 ,

Will ask the IT support team if it is possible to consult with our ISP from HK. I'll send an update here, thanks.

**Comment by neo0000** [comment] 2018-04-17 02:12
Hi @shishirx34 ,

Do you guys have a location restriction?

**Comment by neo0000** [comment] 2018-04-17 03:34
Hi @shishirx34 ,

Seems that we have found the problem. The IT team just noticed today that the IP:  117.18.232.200 is blocked using the HK ISP. Also the said IP is also use for windows update, currently they are using a different ISP if they would like to update their systems here. So now they allow my desktop to access it in both ISP's. 

You may close the issue and thank you for the effort to solve the problem.

**Comment by shishirx34** [comment] 2018-04-17 16:05
Thats good news. I am glad the issue is resolved. Feel free to reach out to us if you have any trouble with the service.

**Closed by shishirx34** 2018-04-17 16:05 UTC
