### ISSUE TITLE
api.nuget.org/v3-flatcontainer/package_name/index.json not working anymore

### ISSUE THREAD

**Issue by janniksam** [NuGet/NuGetGallery#9600] opened 2023-07-31 09:41 UTC
### Impact

I'm unable to use NuGet.org

### Describe the bug

To keep my Azure Devops feed in sync, I used to use the api https://api.nuget.org/v3-flatcontainer/Azure.Identity/index.json once a day to synchronize both feeds.

Recently I've noticed, that the api is giving me nothing but 404s anymore. Is there any alternative or is this a temporary issue?

### Repro Steps

1. Open the url https://[api.nuget.org/v3-flatcontainer/Azure.Identity/index.json](https://api.nuget.org/v3-flatcontainer/Azure.Identity/index.json
2. 404.

### Expected Behavior

I used to get a list of all the package versions. I also used to be able to download the nugets like this:
`var getPackageUrl = $"https://api.nuget.org/v3-flatcontainer/{package.name}/{version}/{package.name}.{version}.nupkg";`

### Additional Context and logs

> <Error>
> <Code>BlobNotFound</Code>
> <Message>The specified blob does not exist. RequestId:7760f770-f01e-0016-1593-c34b20000000 Time:2023-07-31T09:42:17.4213953Z</Message>
> </Error>

**Comment by janniksam** [comment] 2023-07-31 10:04
I did find the issue. It seems like it must be all lower case now, did someone change that recently?

**Comment by joelverhagen** [comment] 2023-07-31 17:22
> I did find the issue. It seems like it must be all lower case now, did someone change that recently?

Hey @janniksam, we have multiple CDN providers and unfortunately this behavior varies across them (some CDNs are case sensitive, others are not). The documented protocol specifies the package ID must be lowercased and this is the behavior the NuGet client SDK implements.

The API docs are here: https://learn.microsoft.com/en-us/nuget/api/package-base-address-resource#request-parameters

This is a duplicate of https://github.com/NuGet/NuGetGallery/issues/9105.

**Closed by joelverhagen** 2023-07-31 17:22 UTC
Labels: Type:Bug
