### ISSUE TITLE
Inconsistent display order of package owner in gallery

### ISSUE THREAD

**Issue by JamesNK** [NuGet/NuGetGallery#6614] opened 2018-10-31 02:37 UTC
The display order of owners is inconsistent on nuget.org between pages.

Package list:
![image](https://user-images.githubusercontent.com/303201/47762730-b5970500-dd22-11e8-8eff-c944c0e58367.png)

Package details:
![image](https://user-images.githubusercontent.com/303201/47762630-56d18b80-dd22-11e8-8b08-c4c392d061ae.png)

Manage packages:
![image](https://user-images.githubusercontent.com/303201/47762706-9ac49080-dd22-11e8-87a5-dd8250196141.png)

**Comment by joelverhagen** [comment] 2018-10-31 06:06
Oh, nice order on manage packages has the problem too. Nice catch.

Duplicate of https://github.com/NuGet/NuGetGallery/issues/6258.

**Closed by joelverhagen** 2018-10-31 06:06 UTC
