### ISSUE TITLE
Historical package download counts data

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5222] opened 2018-01-02 21:49 UTC
As far as I can tell, there's no way to get historical statistics data outside of the "last six weeks".

For example, if I wanted to track the downloads of a package every day, I currently need to constantly monitor the stats page and save the values somewhere, or I need to give up and just look at the last six weeks as a whole.

Another example is that we wanted to know how many downloads NuGet.org had at the end of 2017, but since we didn't spend NYE refreshing the Gallery's statistics, we aren't sure the exact number.

We should show the daily values for at least the last couple weeks.

Another thing to note is that the statistics job doesn't save snapshots of these reports, so we don't even have internal copies of the past data.

**Comment by robertmuehsig** [comment] 2019-04-08 21:59
Related: https://github.com/NuGet/NuGetGallery/issues/4769

**Comment by bruno-garcia** [comment] 2019-08-01 20:00
There's a community take on it: https://github.com/NuGetTrends/nuget-trends

https://nugettrends.com

**Comment by joelverhagen** [comment] 2021-03-22 16:36
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4769.

**Closed by joelverhagen** 2021-03-22 16:36 UTC
Labels: Area: Statistics, Priority - 2
