### ISSUE TITLE
Unable to submit package in Safari

### ISSUE THREAD

**Issue by bijington** [NuGet/NuGetGallery#7037] opened 2019-04-02 20:37 UTC
I have been trying to upload a nuget package through Safari (11.1.2), it lets me select the `.nuspec` file and then press Submit. Eventually the web page stops submitting and returns to show the Submit button again.

I have also confirmed that it fails on the [test site](https://int.nugettest.org/packages/manage/upload).

The following error can be seen in the Console:
```
[Error] Failed to load resource: The network connection was lost. (verify-upload, line 0)
```

NOTE that uploading the same package through Chrome worked almost instantly. I would be happy to supply the package `.nuspec` file if it helps.

**Comment by ryuyu** [comment] 2019-04-03 00:15
Hey! I was unable to reproduce the error you were seeing. It would be great if you could supply the nuspec so I can look into this further.

Thanks!

**Comment by bijington** [comment] 2019-04-03 19:55
I know I suggested providing the nuspec file but I have also attached the nupkg (requires a rename from .zip) file that I was uploading in case that helps.
[Expressive.txt](https://github.com/NuGet/NuGetGallery/files/3040489/Expressive.txt) rename to Expressive.nuspec
[ExpressiveParser.1.4.0.zip](https://github.com/NuGet/NuGetGallery/files/3040487/ExpressiveParser.1.4.0.zip) rename to ExpressiveParser.1.4.0.nupkg

**Comment by ryuyu** [comment] 2019-04-12 23:38
Sorry for the slow turnaround on this.
I have used your nuspec to create a test package and I still have been unable to reproduce the issue you are seeing. The upload goes through successfully on Safari 12.1 (14607.1.40.1.4) on macOS v10.14.4.

Could you grab a network trace for me using the Network tab in the safari dev tools if you can reproduce this?
What version of macOS/Safari are you on?

Thanks!

**Comment by bijington** [comment] 2019-04-24 19:32
Hello sorry for the delay on my part I was stuck on a beach. 

Using the supplied nupkg file I am able to reproduce this consistently on my development machine. I am current running macOS v10.13.6 and Safari 11.1.2. Unfortunately I am prevented from installing further updates at present as the update process fails.

[Here is the network trace from Safari as requested](https://github.com/NuGet/NuGetGallery/files/3113894/int.nugettest.org.zip). You just need to rename from .zip to .har.

Any more info please let me know.

**Comment by ryuyu** [comment] 2019-04-24 21:05
This appears similar to the issue mentioned in this StackOverflow thread (https://stackoverflow.com/questions/42434810/safari-ajax-bug-failed-to-load-resource).

Could you also send us a trace from Chrome so we can compare and see what the difference is between the two traces? Hopefully, that will help us pinpoint if this is something that we can fix on our side.

**Comment by bijington** [comment] 2019-04-25 19:23
Here you go. I had to use an older nupkg but I believe it should still show what you need.

[chrome int.nugettest.org.zip](https://github.com/NuGet/NuGetGallery/files/3118543/chrome.int.nugettest.org.zip) You just need to rename from .zip to .har.

**Comment by ryuyu** [comment] 2019-06-04 22:53
Unfortunately, this seems to be an issue that is unique to Safari.
There doesn't appear to be anything we can do to mitigate this on our side without degrading the experience for others.
I'm sorry for the inconvenience here, and the delay on the response.

I'm going to close this for now, but feel free to reach out again if you have further issues.

**Closed by ryuyu** 2019-06-04 22:53 UTC
Labels: Customer Issue
