### ISSUE TITLE
Measure E2E latency in V3

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2479] opened 2015-05-15 18:32 UTC
We need to measure the time it takes for a newly uploaded package to appear in catalog --> Lucene --> Registration blob and when it is available for download via V3 endpoint. There should be some bench mark around it and we need to see if we are meeting those requirements.

**Comment by maartenba** [comment] 2015-08-18 10:27
Was this one finished? If so please go ahead and close the issue.

**Comment by skofman1** [comment] 2016-10-17 21:09
Duplicate of this: https://github.com/NuGet/NuGetGallery/issues/3239

**Closed by skofman1** 2016-10-17 21:09 UTC
Labels: Area: V3 Feed
