### ISSUE TITLE
[Organization] Blank page modificationa

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#5824] opened 2018-04-18 23:46 UTC
Move the organization help text at the top and another text before the Add new org button:

![image](https://user-images.githubusercontent.com/14800916/38963696-11951f58-4328-11e8-8a8a-8e365889510b.png)

**Comment by scottbommarito** [comment] 2018-04-27 22:45
Dupe of https://github.com/NuGet/NuGetGallery/issues/5770

**Closed by scottbommarito** 2018-04-27 22:45 UTC
