### ISSUE TITLE
Organizations - member add should be able to lookup via email address, not just nuget.org username

### ISSUE THREAD

**Issue by rrelyea** [NuGet/NuGetGallery#5815] opened 2018-04-17 22:24 UTC
Adding members to the NuGet organization, I had difficulty adding my team members.

I didn't know many of their NuGet usernames.
I did know all of their email addresses.

Since they had AAD joined their usernames, this would have been much more usable for me if I could just type in their email address. Then nuget.org would find the appropriate username.

(That said, even more awesome, would be if I could point NuGet towards a security group in AAD, and if it would automatically make members of that contributors.)

**Comment by scottbommarito** [comment] 2018-04-17 22:27
This is a good idea. This could apply to the transform flow as well.

We were considering the AAD integration you suggested, but determined it was too complex for the initial release. In the future we may add such support, but it's already on our backlog.

**Comment by anangaur** [comment] 2018-04-17 23:00
@rrelyea This was my original spec! :) 

You transform and it auto fetches all the folks in the DL and add them as members. May be we should revisit it in the future.

We also had the ability to search via email address but this was raised as a privacy concern that somebody can use this technique to know which emails are accounts on NuGet.org. We do not disclose account email address anywhere.

The following experience can work though:
You can search using email address too. The UI shows a row for the email address as pending.
Behind the scenes if the user is there with the email address, we add the user and send him/her a mail for confirmation. If the user with that email address does not exist, we send him/her a link, clicking which lets him/her create an account and then accept/reject membership. 
Not for MVP though :)

**Comment by skofman1** [comment] 2018-08-29 20:55
This is a duplicate of: https://github.com/NuGet/NuGetGallery/issues/6133
The decision in the other thread was to improve error messages but not to allow adding users by e-mail.

**Closed by skofman1** 2018-08-29 20:55 UTC
Labels: Area: Gallery UI, UI improvement
