### ISSUE TITLE
[NuGet.org Bug]: 

### ISSUE THREAD

**Issue by soumyashree-code** [NuGet/NuGetGallery#9521] opened 2023-06-08 15:15 UTC
### Impact

It's more difficult to complete my work

### Describe the bug

https://api.nuget.org/v3/index.json

### Repro Steps

.

### Expected Behavior

I am creating docker images for my authentication and authorization project am not able to produce all expected images or container 

### Screenshots

![20230608_201452](https://github.com/NuGet/NuGetGallery/assets/135006031/94249499-8a34-4c7b-99ab-acbead578b43)

**Comment by joelverhagen** [comment] 2023-06-09 15:13
Hey @soumyashree-codem, I see in the screenshot you're using Alpine Linux as your base image. Would it be possible for you to try one of the Ubuntu or Debian base images? There is a known deficiency in the Alpine distro related to DNS resolution over TCP. The impact of this deficiency on NuGet.org is that in some regions and CDN configurations, our DNS CNAME chain for api.nuget.org exceeds the maximum for Alpine DNS resolution. This causes problems for other web services and cloud providers (as shown on some AWS public docs, for example) so our best recommendation at this time is to work around the problem with non-Alpine distros. 

Here is a thread with more context: https://github.com/NuGet/NuGetGallery/issues/9396.

I will close this issue as a duplicate of the other.

**Closed by joelverhagen** 2023-06-09 15:13 UTC
Labels: Type:Bug
