### ISSUE TITLE
Markdown Package Documentation image not shown

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#4873] opened 2017-10-19 19:51 UTC
Related to the package & readme.md file from this one:
https://github.com/NuGet/NuGetGallery/issues/4867

It seems our Logo is not recognized from NuGet:

![image](https://user-images.githubusercontent.com/756703/31791040-a71f6e6a-b517-11e7-871d-5cd5f5895c10.png)

But looks fine inside GitHub:

![image](https://user-images.githubusercontent.com/756703/31791056-b4adea8e-b517-11e7-85ee-dc41907d5592.png)

Or is this feature not supported?

**Comment by robertmuehsig** [comment] 2017-10-27 05:37
Oh - maybe the issue pops up, because we moved the repo from a personal account to its own organization. The generated URL is this:
<img src="https://github.com/GregorBiswanger/Electron.NET/blob/master/assets/images/electron.net-logo.png" alt="Electron.NET Logo">

But it is moved to this:
https://github.com/ElectronNET/Electron.NET/blob/master/assets/images/electron.net-logo.png

I will try to update the logo with the "correct" URL - maybe this will fix it.

**Comment by chenriksson** [comment] 2017-10-27 16:57
@robertmuehsig The issue is that the md image link points at the GitHub path, not the raw image. I'm guessing that GitHub resolves these during md rendering. Notice that if you visit the raw .md, the browser won't display the image either:
- https://raw.githubusercontent.com/ElectronNET/Electron.NET/master/README.md

Use the following, and it should work:
- https://github.com/ElectronNET/Electron.NET/raw/master/assets/images/electron.net-logo.png

Closing as by design, as I think we should probably avoid special casing markdown rendering for specific repository types... unless we have enough community feedback to the contrary.

**Closed by chenriksson** 2017-10-27 16:57 UTC
