### ISSUE TITLE
Transform user to organization flow has unhelpful message when non-admin logs in

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6355] opened 2018-08-29 16:55 UTC
Consider the following flow:

1. User logs into account **A** to starts the transform flow.
1. He specifies account **B** as the admin for the transformed org.
1. He clicks the "Transform" button.
1. Now he has to log in as that admin. On accident, he logs into the wrong account **C** because he clicks "Sign in with Microsoft" and his current MSA is associated with a different (not the admin) user.
1. He sees this generic error. Not very helpful:

![image](https://user-images.githubusercontent.com/94054/44802827-98eb1f00-ab71-11e8-95f6-5cce238d4f48.png)

This message should be improved to say he should have logged in with user **B** instead of user **C**.

We have at least one support request regarding this issue.

**Comment by joelverhagen** [comment] 2018-08-29 16:58
For example, I tried this on our DEV environment.

At this page, I logged in with jver3 instead of jver.

![image](https://user-images.githubusercontent.com/94054/44803008-0dbe5900-ab72-11e8-85ad-0a82d302273c.png)

This resulted in the error page screenshot above.

**Comment by scottbommarito** [comment] 2018-08-29 17:05
dupe of https://github.com/NuGet/NuGetGallery/issues/5862

**Closed by scottbommarito** 2018-08-29 17:05 UTC
