### ISSUE TITLE
V2V3 can't find one result

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2757] opened 2015-10-29 00:54 UTC
V2V3:
http://int-0-v3.cloudapp.net//query?q=nganimate
Return 0 record

But we can use this to find the item.
http://int-0-v3.cloudapp.net//query?q=AnimateCss
Its desription includes the "[nganimate]".

V3:
http://api-v3search-0.nuget.org/query?q=nganimate
Return 1 record

**Comment by johnataylor** [comment] 2015-11-10 01:45
The problem is that [ ] are not removed in the tokenization process. So the token in the index is [ngAnimate] and the query needs to match that.

The fix is to also strip the [ ] characters...  I've also stripped ( ) and { } 

Incidentally I don't see this ever working on api-v3search-0.nuget.org it didn't seem to work there when I tried it. In fact I can't see how it could have worked.

**Comment by maartenba** [comment] 2016-03-14 15:02
Has been fixed with v2v3

**Closed by maartenba** 2016-03-14 15:02 UTC
Labels: 1 - Ready, Area: Search, Area: V3 Feed
