### ISSUE TITLE
[Redesign] Stats graph title does not wrap correctly in iOS Safari

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#4160] opened 2017-06-14 22:11 UTC
This is iPhone7 Plus in Portrait mode. In Landscape mode, the title shows up correctly.

![stats](https://user-images.githubusercontent.com/1646506/27156799-ae820388-5113-11e7-8dcb-75846eb229bc.jpg)

**Comment by ryuyu** [comment] 2017-07-06 20:37
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4190

**Closed by ryuyu** 2017-07-06 20:37 UTC
