### ISSUE TITLE
[NuGet.org Bug]: If package has no dependencies than you can't see which framework it references

### ISSUE THREAD

**Issue by domagojmedo** [NuGet/NuGetGallery#8862] opened 2021-10-29 08:36 UTC
### Impact

It bothers me. A fix would be nice

### Describe the bug

If package has no dependencies than you can't see which framework it references
For example: https://www.nuget.org/packages/NReco.PdfGenerator/

Fuget has net45 correctly listed

### Repro Steps

Open https://www.nuget.org/packages/NReco.PdfGenerator/
Go to dependencies tab
No dependencies is listed

### Expected Behavior

It should say net45 in the above case

### Screenshots

![image](https://user-images.githubusercontent.com/12157224/139403650-5629f165-ec3b-473d-94ea-b1b22462b508.png)

**Comment by sajadbz** [comment] 2021-11-03 07:16
I think it's fixed, because my package show the framework that I used :
![image](https://user-images.githubusercontent.com/57556662/140021306-cc4b0592-ac13-4519-ab50-5efa15d7b49c.png)
or :
![image](https://user-images.githubusercontent.com/57556662/140021400-9493c325-07ff-4c00-b672-f3d75184bdf3.png)

**Comment by domagojmedo** [comment] 2021-11-03 08:56
Unfortunately it's not fixed, found another library https://www.nuget.org/packages/Select.HtmlToPdf/

Seems issue is with full framework packages

**Comment by agr** [comment] 2021-11-04 00:07
Hi. The issue looks like a duplicate of https://github.com/NuGet/NuGetGallery/issues/4843. There is work planned for coming weeks to start surfacing this information in a better way on package details page.

**Closed by agr** 2021-11-04 00:07 UTC
Labels: Type:Bug
