### ISSUE TITLE
dotnet core support for nuget.server

### ISSUE THREAD

**Issue by rohitlodha** [NuGet/NuGetGallery#3251] opened 2016-09-27 16:05 UTC
Are there any plans to support nuget server on core platform?

**Comment by skofman1** [comment] 2016-10-04 00:14
@qianjun22 ?

**Comment by maartenba** [comment] 2016-10-04 05:32
(dupe of https://github.com/NuGet/NuGetGallery/issues/3094)

**Comment by skofman1** [comment] 2016-10-17 18:58
Closing since this is a duplicate.

**Closed by skofman1** 2016-10-17 18:58 UTC
