### ISSUE TITLE
status.nuget.org status coloring scheme needs fix

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4033] opened 2017-05-31 16:59 UTC
If there is an issue impacting any of our online service, the status page should reflect the same status color (yellow/red) till the issue is fixed. We should have the latest message pinned at the top and a link to rest of the messages at the bottom.

**Comment by scottbommarito** [comment] 2017-07-13 22:14
This is a duplicate of https://github.com/NuGet/Engineering/issues/230. I will update the other issue's name to better reflect what it's describing.

**Closed by scottbommarito** 2017-07-13 22:14 UTC
Labels: Area: Status page
