### ISSUE TITLE
Versions show very few characters in package details page when using semver2.0.0 versions

### ISSUE THREAD

**Issue by rrelyea** [NuGet/NuGetGallery#5893] opened 2018-05-07 17:56 UTC
![image](https://user-images.githubusercontent.com/8865080/39716275-b9f70eac-51e4-11e8-9829-e08e7c32d219.png)

Looking at NuGet.Packaging, any packages with prerelease labels in their version, don't show up very well on NuGet gallery.
See attached picture.

4.8.0-previe... (current version)
4.7.0-rtm...
4.70.-rtm...
4.7.0-previe...
4.7.0-previe...

This is likely because we have SemVer 2.0.0 names --- i'd imagine we could show more of the version string...the useful part.

**Comment by rrelyea** [comment] 2018-05-08 21:47
Just talked with @loic-sharma 
I have seen how back our 4.7.0+xxxxxxxxxx version looks now.

I think we should consider hiding "+xxxxxxx" in most places in UI.
Show it in some advanced detail view for a package, if you like.

(we do that in VS Client NuGet UI)

**Comment by rohit21agrawal** [comment] 2018-05-09 01:15
@rrelyea @loic-sharma this is precisely what my feedback was at: https://github.com/NuGet/NuGetGallery/issues/5651

**Comment by skofman1** [comment] 2018-05-18 23:17
This is a duplicate of https://github.com/NuGet/NuGetGallery/issues/5651
Lets discuss there.

**Closed by skofman1** 2018-05-18 23:17 UTC
