### ISSUE TITLE
Nuget.Server: Packages get deleted sometimes after copying them to the packages folder.

### ISSUE THREAD

**Issue by radu-poplicean** [NuGet/NuGetGallery#4855] opened 2017-10-17 15:57 UTC
Hello.
I just created a nuget server a few days ago, using Nuget.Server nuget package version 2.14.1. I have chosen a different folder to store packages - "packageRepo", instead of the default one (edited the webconfig for that).
Everything works fine, except sometimes when I drop a package, or many packages into that folder. When enter the folder again, I see how the newly added packages disappear from the folder and are not moved to any directory, they are completely gone. I've counted the total number of files inside my "packageRepo" directory and it is equal to the number of files prior adding the new package to the packages folder. So, the packages are deleted for some reason. After a few retries, the files will be moved to their own folders and not deleted. 
I have tried with several nuget packages and got the same behavior.
One thing to mention: the packageRepo folder it is shared and mapped as a network location from other machines. I am doing the copy/paste job from another machine, via Network Folder.

Is that a known issue? Could I do anything wrong?

Also, what events trigger the move of the package into its own folder? I have seen that IIS reset trigger that and also accessing the folder through Windows File Explorer. I am not sure about querying the server. Maybe you can add this info to the documentation page because it is really confusing.

**Comment by joelverhagen** [comment] 2017-10-19 22:08
I tried simulating this issue with the described configuration, where `packageRepo` was both pointing to a local directory and to a UNC share. I tried copying packages from another machine and from the server machine to the share. I tried varying batch sizes (1 package, 5 package, 100 packages, 500 packages) and a good variety of package sizes. I was unable to reproduce the issue.

> Also, what events trigger the move of the package into its own folder? I have seen that IIS reset trigger that and also accessing the folder through Windows File Explorer. 

There is a `FileSystemWatcher` (the .NET framework type) that listens to all file system events in the `packageRepo` directory.

Could you try attaching a `Trace` listener and writing trace events to a log file?
https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/trace-listeners

Then, reproduce the issue on your server. Finally, if you could provide the trace logs I can take a look and see if anything is funky.

During your app startup:
```csharp
Trace.Listeners.Add(new TextWriterTraceListener(@"C:\some\path\to\NuGet.Server.log"));
Trace.AutoFlush = true;
```

**Comment by joelverhagen** [comment] 2017-10-26 17:33
Closing until we have more feedback from the customer. @radu-poplicean, please let me know if you can provide this additional information so we can get to the bottom of it!

**Closed by joelverhagen** 2017-10-26 17:33 UTC
Labels: Area: NuGet.Server
