### ISSUE TITLE
Reduce the default segment size in lucene index

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2445] opened 2015-04-28 21:10 UTC
The search service instances goes in to bad state often. We suspect this could be related to the reloading of index and big size of segments file. We need to reduce the default size of the segment file.

**Comment by johnataylor** [comment] 2015-04-28 22:05
Really large segments can fail to load. We should be able to limit the segment size by limiting the count of documents per segment. This code used to work so there is some regression here.

**Comment by johnataylor** [comment] 2015-11-13 00:16
It appears that the merge policy is not being followed when there are deletes included in the commit. Now we  have a lot of deletes because when we add we first DELETE by ID/VERSION and ADD back - this is how we apply updates transactionally to the index.

Perhaps there are problems in the merge policy. Apparently many things are fixed in Lucene 4.8 so this issues can probably wait for our upgrade to that rev.

**Closed** 2016-02-15 10:42 UTC
Labels: Area: Gallery UI, Area: Search, Area: V2 Feed, Area: V3 Feed, Priority - 1
