### ISSUE TITLE
Stats labels not visible on high contrast

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4142] opened 2017-06-14 21:45 UTC
![image](https://user-images.githubusercontent.com/94054/27156021-1df22116-5110-11e7-9ffc-a5d5c888ddd5.png)

https://preview-dev.nugettest.org/stats/packages/?groupby=ClientName

**Comment by ryuyu** [comment] 2017-07-06 20:07
duplicate of https://github.com/NuGet/NuGetGallery/issues/4181

**Closed by ryuyu** 2017-07-06 20:07 UTC
