### ISSUE TITLE
Skip the CDN for nuget.org/nuget.exe

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#1512] opened 2013-08-22 22:06 UTC
We need to skip the CDN when serving nuget.org/nuget.exe, serving it directly from blob storage.  This will allow the new version to be available immediately after pushing NuGet.CommandLine.

**Comment by xavierdecoster** [comment] 2015-09-11 13:24
@deepakaravindr is this one still relevant?

**Comment by TimLovellSmith** [comment] 2015-09-11 14:35
The was issue that there's no good way to tell CDN to refresh a certain URL and start serving latest content there, I expect that hasn't changed.
Have you considered doing anything to work around this from the client side like append a dummy query ?_=uniquifier to force bypassing CDN cache when getting nuget.exe?

**Comment by robertmuehsig** [comment] 2016-11-14 10:51
Just scrolled through old issues: Is this still relevant with dist.nuget.org in place? 

I also noticed that https://nuget.org/nuget.exe will serve version 2.8.6 - is this by design?

**Comment by skofman1** [comment] 2016-11-17 19:10
https://nuget.org/nuget.exe is no longer used. Closing the issue.

**Closed by skofman1** 2016-11-17 19:10 UTC
Labels: Area: Monitoring & Alerting, Priority - 1, Up for Grabs
