### ISSUE TITLE
Newline handling is strange in package READMEs

### ISSUE THREAD

**Issue by alexrp** [NuGet/NuGetGallery#8647] opened 2021-06-20 18:39 UTC
See e.g.: https://www.nuget.org/packages/Zig.Toolset.linux-arm

![image](https://user-images.githubusercontent.com/44076/122684649-e3e4ee00-d206-11eb-9904-4982b26bb474.png)

The source README file is here: https://raw.githubusercontent.com/alexrp/zig-msbuild-toolsets/master/README.md

Presumably, the Markdown renderer just turns newlines inside paragraphs into `<br />` elements unconditionally. This results in rather ugly rendering as seen in the example above and is out of line with the vast majority of Markdown renderers.

**Comment by skofman1** [comment] 2021-06-21 18:28
@alexrp , thanks for reporting! We will take a look in July. If you are interested in sending a PR to fix this issues, we will gladly work with you on this :)

**Comment by joelverhagen** [comment] 2021-06-29 20:17
Thanks @alexrp! We've looked at this issue and it seems to have the same root cause as https://github.com/NuGet/NuGetGallery/issues/8642. We'll close this issue as a duplicate for now and re-open later if we find out it's a different problem.

**Closed by joelverhagen** 2021-06-29 20:17 UTC
Labels: Type:Bug, UI improvement, Up for Grabs
