### ISSUE TITLE
can not deploying to docker

### ISSUE THREAD

**Issue by wushilong** [NuGet/NuGetGallery#4335] opened 2017-07-06 10:51 UTC
nuget.server can not deploying to docker
(centos7,mono-complete)

**Comment by skofman1** [comment] 2017-07-08 00:37
Duplicate of: https://github.com/NuGet/NuGetGallery/issues/3899

**Closed by skofman1** 2017-07-08 00:37 UTC
Labels: Area: NuGet.Server

**Comment by mcpdeveloper443** [comment] 2021-01-25 16:32
Please confirm some one , nuget server cannot be deployed into docker yet ??
