### ISSUE TITLE
Consider deleting old test packages

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5174] opened 2017-12-12 17:48 UTC
When logged on as the test account (testnuget@gmail.com), the Gallery is extremely slow and/or non-functional due to the number of packages. We should consider cleaning up old packages from E2E and functional tests, and maybe unlisting the newer packages as well.

Also, we should know the upper limit on # of packages that the Gallery can reasonably support.

Related: https://github.com/NuGet/NuGetGallery/issues/5173

**Comment by joelverhagen** [comment] 2017-12-12 21:13
Closed as duplicate of https://github.com/NuGet/Engineering/issues/497.

**Closed by joelverhagen** 2017-12-12 21:13 UTC
Labels: ClosedAs - Duplicate
