### ISSUE TITLE
Some tests fails due to culture and line endings

### ISSUE THREAD

**Issue by volanavlad** [NuGet/NuGetGallery#7779] opened 2019-12-17 22:12 UTC
### To Reproduce
1. Using this git commit of NuGetGallery '705020bef78e677b41b3303d2eb02c79e165a652'
2. Run tests when current culture is Russian (i.e. ru-...)
3. See:
NuGetGallery.Security.MicrosoftTeamSubscriptionFacts.Policies_ReturnsMicrosoftTeamSubscriptionPolicies:
 Assert.Equal() Failure
                                     ↓ (pos 958)
    Expected: ···r more information.\r\nPolicy violations: {0}"}
    Actual:   ···r more information.\nPolicy violations: {0}"}
                                     ↑ (pos 958)

NuGetGallery.Packaging.PackageMetadataFacts.ThrowsForEmptyAndNonEmptyDuplicatesWhenDuplicateMetadataElementsDetectedAndParsingIsNotStrict
 
    Assert.Equal() Failure
              ↓ (pos 0)
    Expected: An item with the same key has already bee···
    Actual:   Элемент с тем же ключом уже был добавлен.
              ↑ (pos 0)

NuGetGallery.Packaging.PackageMetadataFacts.ThrowsWhenInvalidMinClientVersion(strict: True)
    Assert.Equal() Failure
                                       ↓ (pos 38)
    Expected: ···id version string.\r\nParameter name: value
    Actual:   ···id version string.\r\nИмя параметра: value
                                       ↑ (pos 38)

and so on

### Expected behavior
Tests work OK

### Additional context
It would be better to have localized strings in test asserts where it causes test failures.

**Comment by skofman1** [comment] 2020-02-25 23:03
@agr analyzed the issue and recommended a fix:

I installed the Russian language pack in Windows and managed to reproduce the test failures due to exception text localization. All but two failures are due to, in my opinion, a bit too strict Assert.Equals(expectedMessage, ex.Message), which can be replaced with Assert.StartsWith(expectedStart, ex.Message) which would not include the new line characters and the "Parameter name" tail of the message (which gets localized).

Out of the remaining two, ThrowsForEmptyAndNonEmptyDuplicatesWhenDuplicateMetadataElementsDetectedAndParsingIsNotStrict should be fixed by setting current thread's UI culture carefully, since if we are expecting certain exception text, we have to eliminate the possible variability. Alternatively, we can file an issue against corefx to introduce a special type of exception for duplicate keys in a dictionary, but I have a feeling that is unlikely to get addressed.

Lastly, WillShowViewWithErrorsIfPackageIdIsBreaksParsing is potentially the tricky one since it seems the actual service code (the one being tested) needs improvement to not bubble service exceptions to the user, but use custom error message instead.

**Comment by joelverhagen** [comment] 2020-04-27 23:16
Another user ran into this: https://github.com/NuGet/NuGetGallery/pull/7942#discussion_r416211046

**Closed** 2020-06-08 22:11 UTC
Labels: Area: Gallery UI, Area: Test Coverage, Up for Grabs
