### ISSUE TITLE
Adding owner to package with no owners shows error message

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7318] opened 2019-07-03 22:53 UTC
### Describe the bug
Adding an owner to a package with no owners succeeds but displays an `Internal Server Error` error message.

### To Reproduce
1. Find a package that's owned by a single account
2. Delete the account that owns the package
3. Add a new owner to the package

### Expected behavior
Adding a new owner to a package with no owners should succeed.

### Screenshots

![image](https://user-images.githubusercontent.com/737941/60629438-9ddcb880-9daa-11e9-96f0-06228d74cad0.png)

### Additional context
N/A

**Comment by scottbommarito** [comment] 2019-07-09 19:43
Another note: the UI probably shouldn't say `Internal Server Error` here if the backend returns a 500.

**Comment by skofman1** [comment] 2019-07-31 17:58
@scottbommarito , perhaps this is a duplicate of https://github.com/NuGet/NuGetGallery/issues/7382?

**Comment by scottbommarito** [comment] 2019-07-31 18:05
It is. Closing as fixed.

**Closed by scottbommarito** 2019-07-31 18:05 UTC
Labels: Area: Gallery UI
