### ISSUE TITLE
Improve searchability on nuget.org

### ISSUE THREAD

**Issue by Eilon** [NuGet/NuGetGallery#4687] opened 2017-09-15 05:34 UTC
_From @ChristopherHaws on September 14, 2017 23:39_

Hello,

I find myself using this library a lot, especially in linqpad scripts when I am testing something out. Currently, pretty much the only way to get this library to return in the nuget search results is by typing the exact name of the entire package `Microsoft.Extensions.DependencyInjection`. It would be nice to have a few more tags added to the packages to improve searchability a bit. Some suggestions I would have are:

- microsoft
- ms
- ioc

Ideally I would like to be able to type `ms ioc` or `ms di` and have it come back as the first result.

Thanks and keep up the great work! 👍 

_Copied from original issue: aspnet/DependencyInjection#582_

**Comment by Eilon** [comment] 2017-09-15 05:37
I completely agree. Even if I type out all the individual parts of the package id I want, but without the dots (e.g. I use spaces), matches aren't found (until like page 50).

Example: I want to find Microsoft.AspNetCore.Mvc:
1. Search for: `microsoft aspnetcore mvc`: https://www.nuget.org/packages?q=microsoft+aspnetcore+mvc
   * The package I want is at the top of page 3: https://www.nuget.org/packages?page=3&q=microsoft%20aspnetcore%20mvc
2. Search for: `microsoft.aspnetcore.mvc`: https://www.nuget.org/packages?q=microsoft.aspnetcore.mvc
   * The package I want is the first match.

**Comment by anangaur** [comment] 2019-04-05 17:30
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4124

**Closed** 2019-08-20 04:37 UTC
Labels: Area: Search, ClosedAs - Duplicate, Type:Feature
