### ISSUE TITLE
Include github.com in the trusted image domains list

### ISSUE THREAD

**Issue by davepermen** [NuGet/NuGetGallery#8652] opened 2021-06-23 10:15 UTC
Github Actions seem to have their Badges stored on github.com directly. 

For https://github.com/conesoft/files it generated it on https://github.com/conesoft/files/actions/workflows/publish.yml/badge.svg, which doesn't render on README.md

### Describe the solution you'd like
Add github.com to the trusted image domain list.

**Comment by augustoproiete** [comment] 2021-06-23 12:35
This looks like a duplicate of https://github.com/NuGet/NuGetGallery/issues/8645

**Comment by joelverhagen** [comment] 2021-06-23 17:27
Yes indeed, @augustoproiete -- thanks for connecting the dots. @davepermen, keep an eye on issue #8645 and PR #8646 for this fix.

I appreciate you including an example URL. I tested it against the new regex in the aforementioned PR and it matches:
![image](https://user-images.githubusercontent.com/94054/123141723-879feb00-d40d-11eb-8a3c-3c6f7787d0fa.png)

I'll close this issue as a duplicate.

**Closed by joelverhagen** 2021-06-23 17:27 UTC
