### ISSUE TITLE
Inconsistent page margins in small window in Edge

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4192] opened 2017-06-14 22:55 UTC
High contrast, but likely would happen in normal mode, too:
https://preview-dev.nugettest.org/policies/About
![image](https://user-images.githubusercontent.com/102933/27158051-b210b58e-5119-11e7-85e5-cfb0d0375125.png)

Notice the text starts right at the left border.
https://preview-dev.nugettest.org/packages/BaseTestPackage/1.0.0/ReportAbuse

![image](https://user-images.githubusercontent.com/102933/27158064-c7a56dea-5119-11e7-9524-860d7f44b083.png)

Notice that there is a little space between the page border and text border.

**Comment by scottbommarito** [comment] 2017-06-30 21:32
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4179

**Closed by scottbommarito** 2017-06-30 21:32 UTC
