### ISSUE TITLE
[NuGet.org Bug]: README doesn't render comments in code blocks

### ISSUE THREAD

**Issue by danielchalmers** [NuGet/NuGetGallery#9187] opened 2022-08-10 06:50 UTC
### Impact

It bothers me. A fix would be nice

### Describe the bug

Comments in XAML code blocks aren't rendered.

### Repro Steps

Example to include in README:

\```xaml
xmlns:wp="clr-namespace:WpfWindowPlacement;assembly=WpfWindowPlacement"

\
wp:WindowPlacementProperties.Placement="{Binding MyPlacement}"
\```

### Expected Behavior

Comment `Update size, position, and state on SourceInitialized and Closing` is rendered.

### Screenshots

NuGet  
![image](https://user-images.githubusercontent.com/7112040/183833933-e61f4a13-b13c-4b87-bba5-52b0c0e1e99d.png)

GitHub  
![image](https://user-images.githubusercontent.com/7112040/183833756-6959ddc4-cbc8-4c95-85cf-4384e30c86f9.png)

### Additional Context and logs

Example package with XAML codeblock and comment: https://www.nuget.org/packages/wpfwindowplacement/4.0.2

Example package with XML codeblock and comment: https://www.nuget.org/packages/blazorwasmprerendering.build/1.0.0-preview.4.1

**Comment by joelverhagen** [comment] 2022-08-25 14:08
Thanks for the bug report @danielchalmers! This is indeed an issue and it extends beyond XAML code blocks. For example, this package uses XML (a recognized syntax highlight which XAML is not) and comments are hidden.

My guess is that the custom HTML sanitizer that's blocking https://github.com/NuGet/NuGetGallery/issues/8644 is also removing these code comments.

**Comment by joelverhagen** [comment] 2022-08-25 19:36
This is a duplicate of https://github.com/NuGet/NuGetGallery/issues/9060.

**Closed by joelverhagen** 2022-08-25 19:36 UTC
Labels: Type:Bug, Readme
