### ISSUE TITLE
FindByUsername and FindByKey should not return records that are marked as deleted.

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#5569] opened 2018-03-02 01:09 UTC
UserService FindByUsername and FindByKey should not return records that are marked as deleted.

**Comment by skofman1** [comment] 2018-03-15 00:08
@cristinamanum , this might be intentional behavior of the code. 
Feel free to refactor if you like. Closing the issue since this is not a bug/feature suggestion.

**Comment by cristinamanum** [comment] 2018-03-17 02:20
Reopen and add customer impact.
If a deleted user is added added as an owner to a package the below is the error. The actual behavior should be that the owner does not exists.

![image](https://user-images.githubusercontent.com/16580006/37550692-e2c2f648-294e-11e8-9ddf-73f09fb0ea7c.png)

**Closed** 2018-05-21 17:28 UTC
Labels: Area: Gallery UI, Type:Bug, Verified-Dev, Verified-Int
