### ISSUE TITLE
Changed Package Titles don't Show Up in Search Results

### ISSUE THREAD

**Issue by dvanlant** [NuGet/NuGetGallery#3176] opened 2016-08-01 18:17 UTC
I recently added a few packages and changed the titles.  I noticed that the old package names still show up in the search results for the package even though the titles have been updated. Below is an example package for which this bug occurs.

https://www.nuget.org/packages/DOTSAddressValidation3US/

**Comment by maartenba** [comment] 2016-08-01 23:38
Duplicate of https://github.com/NuGet/NuGetGallery/issues/3168 (same issue). Please push the packages with the correct title in the .nuspec for now until we get the fix released.

**Closed by maartenba** 2016-08-01 23:38 UTC
