### ISSUE TITLE
Admin/Support Request pages do not have the new site design

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#4739] opened 2017-09-25 19:01 UTC
The admin, SR pages and maybe more do not have the new site redesign. I am not sure if this is expected. Filling a bug to get clarity.

**Comment by skofman1** [comment] 2017-10-21 07:36
Duplicate of this: https://github.com/NuGet/NuGetGallery/issues/4120

**Closed by skofman1** 2017-10-21 07:36 UTC
Labels: Area: Gallery UI, Pillar: Experience
