### ISSUE TITLE
search service returns 500 for malformed queries

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2544] opened 2015-06-10 18:21 UTC
q=Tags:"-" and q="xxx returns 500. We need to fix it.

**Comment by maartenba** [comment] 2015-06-10 18:46
Duplicate of https://github.com/NuGet/NuGetGallery/issues/2537

**Closed** 2015-06-11 20:56 UTC
Labels: Area: V2 Feed

**Comment by maartenba** [comment] 2015-06-12 06:28
Any related commits?
