### ISSUE TITLE
Manage Packages page should be sorted

### ISSUE THREAD

**Issue by jonwchu** [NuGet/NuGetGallery#4407] opened 2017-07-18 00:53 UTC
When you navigate to the "Manage Packages" page, the listing of packages you own seems to be in no particular order. It would be helpful to have this sorted by some means, like alphabetical or last publish date to make it easier to find the package you want to manage.

**Comment by joelverhagen** [comment] 2017-07-21 23:52
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4431.

**Closed by joelverhagen** 2017-07-21 23:52 UTC
Labels: ClosedAs - Duplicate
