### ISSUE TITLE
[Feature]: Deep link Release Notes and show in Package Manager

### ISSUE THREAD

**Issue by SerratedSharp** [NuGet/NuGetGallery#9029] opened 2022-03-02 00:18 UTC
### Related Problem

Release Notes seems like a good place to put important information about changes in the current release but this isn't very visible.  It doesn't appear when the package is selected in the VS Package Explorer, and I can't deeplink to it.

There's already a hash link for the tab, but it doesn't activate the tab: https://www.nuget.org/packages/SerratedSharp.SerratedJQ.Lite#releasenotes-tab 

### The Elevator Pitch

In documentation I find myself putting things like "For current compatibility information visit *Nuget link* and click the right Release Notes tab" which has unnecessary exposition rather than what would be more straightforward "For current compatibility information see *Nuget link*". 

To accomplish this, make the hash link deep link directly to Release Notes tab, so that we can link directly to the tab from other places:
https://www.nuget.org/packages/SerratedSharp.SerratedJQ.Lite#releasenotes-tab

Also consider showing the Release Notes as a section in the VS Package Manager when the package is selected.  I.e. in the panel where Description, Version, License, etc. is shown.

Typically Release Notes would contain information about breaking changes which would warrant it being much more visible.

**Comment by loic-sharma** [comment] 2022-03-08 21:11
Hello, thank you for opening this issue! I believe this issue is a duplicate of https://github.com/NuGet/NuGetGallery/issues/8822 and will addressed by this fix: https://github.com/NuGet/NuGetGallery/pull/8860.

I'll go ahead and close this one off for now but please let us know if you have follow up questions or concerns!

**Closed by loic-sharma** 2022-03-08 21:11 UTC
Labels: feature-request
