### ISSUE TITLE
[Organizations] Show packages owned by a user's organizations in their Manage Packages page and allow filtering

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#4894] opened 2017-10-24 18:43 UTC

**Comment by chenriksson** [comment] 2017-12-01 17:56
Moving to S128, since I won't have time to finish the PR in S127 due to on-call responsibilities.

**Comment by chenriksson** [comment] 2017-12-11 23:17
Verification: ensure 'Manage Packages' view still shows user packages; can't verify fully until org onboarding.

**Comment by chenriksson** [comment] 2017-12-13 20:43
Regression #5173 seen when # packages is >3350. Working on a short-term fix to unblock deployment.

**Comment by chenriksson** [comment] 2017-12-13 23:57
Closing - can't verify until we onboard an organization. We'll have a bug bash including this scenario at that time.

I'll use #5173 to track Manage Packages performance updates and to verify that there is no regression.

**Closed by chenriksson** 2017-12-13 23:57 UTC
Labels: Area: Gallery UI, Verified-Dev
