### ISSUE TITLE
Not found nuget/Packages

### ISSUE THREAD

**Issue by artcrespo** [NuGet/NuGetGallery#8068] opened 2020-06-23 18:17 UTC
### Describe the bug
Description is available [here](https://stackoverflow.com/q/60869232/7530449) 

### To Reproduce
Steps to reproduce the behavior are available [here](https://stackoverflow.com/q/60869232/7530449)

### Expected behavior
An OK status code and the list of the packages

### Screenshots
Not applied

### Additional context
Documentation [here](https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server)

**Comment by joelverhagen** [comment] 2020-06-29 19:36
Could you ZIP up your project containing the NuGet.Server reference and attach it to a comment here? I was unable to reproduce the problem.

Please be sure to remove any personally identifiable information or secrets.

Alternatively, you can send send a link to a file sharing website (like OneDrive, Dropbox, etc) containing the ZIP file if you are concerned about sharing the project here.

**Comment by FobbanN12** [comment] 2020-07-07 13:39
I am experiencing the same problem with a freshly generated NuGet server.
Please reach out if you need any additional information.

**Comment by joelverhagen** [comment] 2020-07-07 15:51
Hello @FobbanN12, could you provide the information I mentioned in my [previous comment](https://github.com/NuGet/NuGetGallery/issues/8068#issuecomment-651318014)?

**Comment by FobbanN12** [comment] 2020-07-07 16:59
@joelverhagen  Ok, I'll create a new project following https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server and get back to you soon.

**Comment by FobbanN12** [comment] 2020-07-07 17:26
@joelverhagen I've uploaded the project due to the ZIP being to big to upload here: https://gofile.io/d/D3ZjKu

**Comment by joelverhagen** [comment] 2020-07-10 17:29
@FobbanN12, this is because your project is a VB.NET project. Currently, only C# projects are supported out of the box. This is because the NuGet.Server package drops a "NuGetODataConfig.cs" file in your project that initializes the app. It's possible that you can refactor the C# in that code as VB.NET to make it work, but I've never tried that.

Could you try a C# project and see if you run into the same problem?

**Comment by joelverhagen** [comment] 2020-07-13 16:10
Hello, I will close this issue. If you have any other problems, feel free to open a new issue. Thanks!

**Closed by joelverhagen** 2020-07-13 16:10 UTC
Labels: Area: NuGet.Server

**Comment by FobbanN12** [comment] 2020-07-13 17:03
Didn't notice your answer.
I realize mine and probably many others mistake - not choosing "C#" in the "All languages"-dropdown.

Thanks for your support.
