### ISSUE TITLE
nuget.server Package has missing types

### ISSUE THREAD

**Issue by mwenk** [NuGet/NuGetGallery#3406] opened 2016-12-07 14:54 UTC
I tried to setup a nuget.server and created an empty ASP.NET 4.5.2 Project in VS2015. Then I added the nuget.server package.  The added code won't compile because of various errors. Some usings are non exitent (  Nuget.Server.* ) and several types are missing.

I would have expected that it does compile out of the box.

**Comment by joelverhagen** [comment] 2016-12-08 21:37
This is a duplicate of issue https://github.com/NuGet/NuGetGallery/issues/3257.

There is a bug in 2.12.2 where the package is incorrectly considered compatible with less than .NET 4.6. There are two workarounds until the next version of NuGet.Server is released.

1. Use NuGet.Server version 2.12.1.
1. Make your project target .NET Framework 4.6 or higher.

**Closed by joelverhagen** 2016-12-08 21:37 UTC
