### ISSUE TITLE
Stuck in validating

### ISSUE THREAD

**Issue by dazinator** [NuGet/NuGetGallery#5364] opened 2018-01-28 23:11 UTC
I published a bunch of packages to nuget.org together as can be seen from the bottom of this AppVeyor build log: https://ci.appveyor.com/project/dazinator/dotnettency/branch/develop

Some of them have been indexed, however a few of them still look like this:

![image](https://user-images.githubusercontent.com/3176632/35488406-52f7cb12-0480-11e8-8efe-21c35598a4d1.png)

1. Why the lag?
2. How can I see when the estimated time is when this package will be available? Another developer is halted whilst waiting for this updated package to become available..

**Comment by anangaur** [comment] 2018-01-29 19:23
This should be fixed now. Please reopen if the issue is not resolved.

**Closed by anangaur** 2018-01-29 19:23 UTC
