### ISSUE TITLE
"Import documentation" - part of the .nuspec/.csproj settings?

### ISSUE THREAD

**Issue by mishra14** [NuGet/NuGetGallery#4920] opened 2017-10-27 00:29 UTC
_From @robertmuehsig on October 25, 2017 21:17_

Everytime I update my NuGet package via the WebUI upload I need to reenter the documenation url. I know this is a pretty new feature, but is there some kind of PackageDocumentation tag that I can use so that I don't have to reenter the GitHub URL each realease?

![image](https://user-images.githubusercontent.com/756703/32023766-9743dc7a-b9da-11e7-9306-68908dfe08f9.png)

_Copied from original issue: NuGet/Home#6103_

**Comment by mishra14** [comment] 2017-10-27 00:31
cc: @joelverhagen @chenriksson

**Comment by joelverhagen** [comment] 2017-10-27 00:49
AFAIK this is by design, for this "minimal viable product" version of this feature. @chenriksson can give the full story here.

@robertmuehsig, would a new version defaulting to the previous version's documentation be acceptable? More formally, when handling a new version upload, inherit the readme of a version less than the version being pushed, if any exists. This is just a suggest and might clash with plans I don't know about. If we go this route, we would have to choose between baking this in at upload time or just falling back in the package details view if the selected version has no readme.

**Comment by joelverhagen** [comment] 2017-10-27 00:52
Related: https://github.com/nuget/nugetgallery/issues/4730

**Comment by robertmuehsig** [comment] 2017-10-27 05:39
"would a new version defaulting to the previous version's documentation be acceptable? " => This is what I was expecting 👍

**Comment by chenriksson** [comment] 2017-10-27 16:15
@mishra14 @joelverhagen This is by design for MVP. This feature was originally intended as a GitHub integration, where we would surface a repository URL and pull in the README.md. The focus shifted as we debated whether the .md should eventually be packed directly into the .nupkg, and whether it should be the README.md or something more consumer focused (e.g., documentation.md). I think this issue is a dupe of #4730 

@robertmuehsig We've also discussed this: having a default for all versions, or having it use the documentation from the most recent version. If this remains a Gallery-only experience for a while, then this may be a possibility. We actually have an issue for this: #4772 

We certainly would love to hear community feedback, which you can provide on either #4772 or #4730

**Comment by skofman1** [comment] 2017-10-27 16:27
Per @chenriksson response, I'm closing this issue as duplicate since it's already tracked by  #4772 and #4730

**Closed by skofman1** 2017-10-27 16:27 UTC
Labels: Area: Gallery UI
