### ISSUE TITLE
Markdown Package Documentation is HTML escaped

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#4867] opened 2017-10-19 06:33 UTC
Hi
I was using the new package documentation feature and just linked the [raw GitHub Repo](https://github.com/ElectronNET/Electron.NET/blob/master/README.md) Readme.md file, but unfortunatly < and > and " are HTML escaped:
https://www.nuget.org/packages/ElectronNET.API/

![image](https://user-images.githubusercontent.com/756703/31757009-521aa7c4-b4a7-11e7-881d-db9fd1c1f998.png)

On GitHub.com the Readme.md looks as expected:

![image](https://user-images.githubusercontent.com/756703/31757166-0ffd8fc2-b4a8-11e7-84cf-32182413b709.png)

**Comment by chenriksson** [comment] 2017-10-19 17:49
@robertmuehsig Thanks for reporting, we have a fix in the works!

Closing as duplicate of #4783

**Closed by chenriksson** 2017-10-19 17:49 UTC
