### ISSUE TITLE
Package upload metadata verification page does not render newlines

### ISSUE THREAD

**Issue by SteveWilkes** [NuGet/NuGetGallery#5215] opened 2017-12-20 22:03 UTC
Hi,

I just spent way too long realising that just because newlines (in my case in release notes) aren't rendered on the package upload metadata verification page, doesn't mean they aren't rendered on the package listing page.

To avoid confusion, the rendering should be consistent between the two pages.

**Comment by skofman1** [comment] 2018-01-04 23:51
@SteveWilkes , what is the package you uploaded? I would like to repro the issue and need an example.

**Comment by SteveWilkes** [comment] 2018-01-06 16:15
Hi!

The package in question was the latest version of https://www.nuget.org/packages/AgileObjects.ReadableExpressions, but I would assume it happens for any package you upload which has newlines in the release notes.

**Comment by loic-sharma** [comment] 2021-04-26 20:46
Hello, it looks like this issue is fixed on the latest version of nuget.org:

![image](https://user-images.githubusercontent.com/737941/116148367-ae53d680-a695-11eb-9592-24437f5bfd00.png)

Are you able to reproduce this problem still @SteveWilkes? Please let us know and we'll take another look!

**Closed** 2021-04-26 21:18 UTC
Labels: Area: Gallery UI, Type:Bug, UI improvement
