### ISSUE TITLE
-PreRelease flag not compatible with specifying a specific version

### ISSUE THREAD

**Issue by tubwreck** [NuGet/NuGetGallery#2444] opened 2015-04-28 11:48 UTC
My package feed contains the following items:

    myPackage.8.5.0-b000069.nupkg
    myPackage.8.5.1-b000022.nupkg
    myPackage.8.5.1-b000023.nupkg
    myPackage.8.5.0-b000075.nupkg
    myPackage.8.5.0-b000076.nupkg

That is, I'm currently building pre-release builds of two versions of myPackage (8.5.0 and 8.5.1).

I need a nuget.exe command line that will get the most recent prerelease of 8.5.0 (but not 8.5.1). I've tried various combinations of things, but can't figure out how to do it.

This command:

    nuget install -PreRelease -Version 8.5.0 myPackage 

complains that there is no 8.5.0 package (true, since I'm still building prereleases).

If I omit the -Version option, then it will happily install myPackage.8.5.1-b000022.nupkg (because it's the newest), but that's not what I want. I want the newest 8.5.0 build.

If I create a dummy myPackage.8.5.0, then the command

    nuget install -PreRelease -Version 8.5.0 myPackage

will install the 8.5.0 package and ignore the pre-release package versions.

**Comment by deepakaravindr** [comment] 2015-04-30 20:47
Duplicate of https://github.com/NuGet/Home/issues/503. Thanks!

**Closed by deepakaravindr** 2015-04-30 20:47 UTC
Labels: Non Gallery Issue - Move to Home
