### ISSUE TITLE
api/v2/curated-feeds/whatever responds with HTTP 200

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#3989] opened 2017-05-18 18:34 UTC
For some reason, the requests like

    https://www.nuget.org/api/v2/curated-feeds/almost-anything

respond with HTTP 200 instead of 404. We probably need to look into that.

**Comment by skofman1** [comment] 2017-06-07 16:58
@emgarten , is this by design?

**Comment by emgarten** [comment] 2017-06-07 20:07
> is this by design?

Not that I know of. The client uses curated feeds in the same way as other feeds. It is possible an older version of VS shipped with a curated feed that was removed and the gallery wanted to avoid breaking someone, but that is just a guess.

**Comment by skofman1** [comment] 2017-06-07 20:31
Since this behavior isn't impacting customers in a negative way, and changing it is a risk, closing this issue.

**Closed by skofman1** 2017-06-07 20:31 UTC
