### ISSUE TITLE
Deprioritizing "advanced" package in search results

### ISSUE THREAD

**Issue by svick** [NuGet/NuGetGallery#9485] opened 2023-04-26 09:11 UTC
We have a product called "Metalama", with several packages on NuGet, two of them are of interested today:

* `Metalama.Framework`: the main package most people should be using, depends on `Metalama.Compiler`.
* `Metalama.Compiler`: advanced package, most people don't even need to know this package exists, some advanced users will only use this package.

[When I search for "metalama" on nuget.org](https://www.nuget.org/packages?q=metalama), the first two results I get are the reverse of what we want:

![](https://user-images.githubusercontent.com/287848/234526689-18300878-004b-4b0f-a813-d4333cd8fdf5.png)

`Metalama.Compiler` is shown first, presumably because both packages have "metalama" in both the package id and in tags and `Metalama.Compiler` has higher number of downloads (because it's a dependency of `Metalama.Framework`).

Is there something we or the NuGet team can do, so that the `Metalama.Framework` package shows before the `Metalama.Compiler` package? (The ALL CAPS notice on the advanced package that we currently have there does not seem like a great solution.)

**Comment by joelverhagen** [comment] 2023-04-26 14:20
The issue you're describing is this: https://github.com/NuGet/NuGetGallery/issues/7186. I'll close this as a duplicate but will provide you with some context here.

The reason this is happening is because of the download count on Metalama.Compiler is higher than Metalama.Framework and the search query matches the two packages equivalently, so the higher download count wins. Having a higher download count is expected since the Compiler package is a dependency of Framework so any download of Framework would result in a download of Compiler. And for those advanced users, the download count of Compiler will be incremented without Framework.

Unfortunately, there aren't many great options to resolve this problem holistically today. I think there are two ways of approaching the general problem for my team:

1. Discount downloads by reverse dependency. In other words, do some fuzzy logic where the "Compiler" package has its total subtracted by the "Framework" package. This isn't perfect because of download caching (meaning 1 download of "Framework" does not always equal 1 download of "Compiler"). This would require some pretty intense testing since it could back fire in unexpected ways (search relevancy changes often do 😂).
2. Introduce some package metadata where a package can say "don't use me, use other package X" which could be a way of automatically setting up a partial, fair (?) popularity transfer ([a manual process today](https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages#transfer-popularity-to-a-newer-package)). 
3. Totally re-instrument and rework our popularity metric to be based on top-level install rather than any download (transitive or otherwise). This would require changes in the client software, maybe even a new protocol, privacy assessments, etc etc.

Short of these feature enhancements, I can suggest you some of options in the meantime:

- Keep your current approach. To be honest, your note appears to me as quite visible and probably will get the job done.
- Unlist the compiler package. I know, not a great option, but it's technically possible to have an unlisted dependency and restore works just fine.
- You could attempt fiddling with the metadata (such as tags) in Framework so that there is more mention of your expected search terms (e.g. "metalama"). You can try this on our int.nugettest.org environment and look at the `Score` debug property to see how close the two packages are scoring for any query. The current search URL for our INT environment is here: https://azuresearch-usnc.int.nugettest.org/query?q=metalama&prerelease=true&semVerLevel=2.0.0&debug=true (note the `debug=true` parameter). If you can get the score to be significantly higher for one of your packages on INT when the download count for all of the packages is 0, then the same metadata configuration on PROD may work -- although eventually you may fall prey to the same problem again if the Compiler downloads greatly outpace the Framework ones.

I don't think a popularity transfer (https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages#transfer-popularity-to-a-newer-package) is appropriate in this case since the download count of the Compiler package would effectively go to 0. Also, it doesn't adhere to our policy that popularity transfers are meant for deprecation. Transferring popularity from a dependency package to a top-level package is not fair to the competition since it effectively doubles your download count growth and therefore unfairly boosts your popularity.

**Comment by joelverhagen** [comment] 2023-04-26 14:20
Closing as a duplicate of https://github.com/NuGet/NuGetGallery/issues/7186.

**Closed** 2023-04-26 14:20 UTC
