### ISSUE TITLE
Hamburger icon is invisible in small window in Edge in high contrast

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#4186] opened 2017-06-14 22:41 UTC
https://preview-dev.nugettest.org/packages

![image](https://user-images.githubusercontent.com/102933/27157704-e5b85808-5117-11e7-971e-973ea3e8879f.png)

**Comment by joelverhagen** [comment] 2017-06-15 23:54
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4147.

**Closed by joelverhagen** 2017-06-15 23:54 UTC
Labels: ClosedAs - Duplicate
