### ISSUE TITLE
flatcontainer api disregards '.' at the end of the package name

### ISSUE THREAD

**Issue by tkrick** [NuGet/NuGetGallery#6130] opened 2018-07-02 19:06 UTC
**Repro:**
for all package names (newtonsoft.json is just an example):
https://api.nuget.org/v3-flatcontainer/**newtonsoft.json.**/index.json returns the same thing as:
https://api.nuget.org/v3-flatcontainer/**newtonsoft.json**/index.json
even though the package id "newtonsoft.json." does not exist.

Notice also that the nuspec for package id "newtonsoft.json." does not return (it 404s)':
https://api.nuget.org/v3-flatcontainer/newtonsoft.json./3.5.8/newtonsoft.json..nuspec

**Expected**:
https://api.nuget.org/v3-flatcontainer/**newtonsoft.json.**/index.json
should 404

**Comment by loic-sharma** [comment] 2018-07-02 19:12
Weird. Is this causing bugs in any NuGet scenarios?

FYI, the flat container API is really just a public Azure Blob Storage endpoint. I've tested other Azure Blob Storage accounts, this behavior seems to be consistent.

**Comment by tkrick** [comment] 2018-07-02 19:39
I am working on VSTS packaging server product and hitting this as part of our upstream feature. When reaching out to the various upstreams we eat 404s from the index.json and skip that upstream, but we do not eat 404s from fetching the nuspec because we expect that if the server says it has that version that we should be able to get the nuspec. 

That said, we are also considering just returning 404 up front and not caring about populating upstream metadata lazily when the package name is not valid (i.e. does not fits regex: @"^\w+([_.-]\w+)*$") in all of our apis to work around this. Right now we only do that check on explicit ingestion not lazy upstream metadata population.

**Comment by loic-sharma** [comment] 2018-07-02 20:28
I see. It sounds like validating the package name before reaching out to upstreams is a good solution to your problem. I'll close this issue as we cannot easily fix this and it shouldn't affect NuGet client customers. Please let us know if you have any additional questions or concerns!

**Comment by tkrick** [comment] 2018-07-02 21:12
can you give some indication why nuget.org treats the . appended url and w/o the dot as the same package id? I can't imagine it is azure blob that does this. 

also, i'd also note perhaps closing this is a bit premature (granted it is low pri). for instance this is public facing if you put a dot at the end of a package name it still attempts to fetch versions, finds them and then says the latest version does not exist:
[02:09][2][1] E:\Tools\VsoNuget > .\nuget4_3.exe install newtonsoft.json. -Source nuget.org
Feeds used:
  https://api.nuget.org/v3/index.json

  GET https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json./index.json
  **OK https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json./index.json 359ms**


Attempting to gather dependency information for package 'newtonsoft.json..11.0.2' with respect to project 'E:\Tools\VsoNuget', targeting 'Any,Version=v0.0'
Package **'newtonsoft.json. 11.0.2'** is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources are available (OR) package id, version are specified correctly

**Comment by loic-sharma** [comment] 2018-07-02 22:32
Apologies, you're right, this does affect the NuGet client. I'll reopen this issue until we figure out how we want to handle this.

This behavior is indeed because of Azure Blob Storage, see:

https://nugetint0.blob.core.windows.net/v3-flatcontainer/newtonsoft.json/index.json
https://nugetint0.blob.core.windows.net/v3-flatcontainer/newtonsoft.json./index.json

These endpoints are from a public Azure Blob Storage container. I've contacted Azure Blob Storage support as I cannot find documentation that explains this behavior.

I've also opened this issue on the NuGet client: https://github.com/NuGet/Home/issues/7083

**Comment by loic-sharma** [comment] 2018-07-02 22:34
This also affects registration and catalog endpoints as these are hosted on Azure Blob Storage.

**Comment by loic-sharma** [comment] 2018-07-03 18:41
I received confirmation from Azure Support that this is expected behavior as directory names cannot end with a period: https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#naming-conventions

**Comment by tkrick** [comment] 2018-07-03 18:50
good enough. i would content that if end periods are not allowed in directory names then the request should return bad request, not map to a directory name without the period.

**Comment by loic-sharma** [comment] 2018-07-03 19:53
I agree that the request shouldn't succeed if the URI is malformed. However, fixing this from nuget.org's side is difficult with our current infrastructure. After talking to the team, we agree that all NuGet clients should validate package names before performing network calls to NuGet servers.

I verified that:

1. There are no packages on nuget.org with a name that ends with a period
2. On upload, nuget.org validates the package id properly (see [this code](https://github.com/NuGet/NuGetGallery/blob/7e0f3c7af27a0a12cdec012a39f78fafab28b0a4/src/NuGetGallery.Core/Packaging/ManifestValidator.cs#L50))

With all of that, are you okay with me closing this issue @tkrick?

**Comment by tkrick** [comment] 2018-07-03 21:16
@loic-sharma yep go ahead and close. client fix is good enough. if i feel strongly about the azure thing i might file an issue with them to return BadRequest.

**Comment by loic-sharma** [comment] 2018-07-03 21:29
Sounds good. Thanks for your help!

**Closed by loic-sharma** 2018-07-03 21:29 UTC
