### ISSUE TITLE
Support requests does not properly handle Chinese characters

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4553] opened 2017-08-14 15:50 UTC
![image](https://user-images.githubusercontent.com/94054/29279724-9f872c20-80cd-11e7-91cc-b4f5a38ea648.png)

Those question marks are actually Chinese characters. They appear as question marks.

**Comment by skofman1** [comment] 2017-09-20 06:01
Duplicate of this: https://github.com/NuGet/NuGetGallery/issues/4275

**Closed by skofman1** 2017-09-20 06:01 UTC
Labels: Area: Gallery UI, Priority - 3
