### ISSUE TITLE
Suggestion: add bookmarks/favorites on the nuget.org

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/NuGetGallery#3808] opened 2017-04-20 10:37 UTC
It'd very helpful if people could bookmark packages on nuget.org site. 
Like we could do on https://www.npmjs.com/ for example.

**Comment by robertmuehsig** [comment] 2017-04-20 14:31
I guess this issue is more or less the same as this (very) old one https://github.com/NuGet/NuGetGallery/issues/440

**Comment by evil-shrike** [comment] 2017-04-20 14:35
yeah, exactly, I was searching for "favorite" not "favourite" :(

**Comment by skofman1** [comment] 2017-04-20 17:46
Thanks for the feedback @evil-shrike . Closing this issue as duplicate of: https://github.com/NuGet/NuGetGallery/issues/440

**Closed by skofman1** 2017-04-20 17:46 UTC
