### ISSUE TITLE
How to create NuGet API V3 feed

### ISSUE THREAD

**Issue by NagarajMasub** [NuGet/NuGetGallery#2968] opened 2016-04-04 08:48 UTC
Hi,
Now we have our own nuget feed using NuGet.Server v2.10.1 , we are facing issue in installing UWP NuGet packages, the packages listed in Visual studio but cant able to install getting not found error, after referred in some sites, they told to use nuget api v3 tokens for vs2015 packages, how can i create Nuget API v2 and V3 API and provide separate nuget links.. as like in the myget nuget feed

**Comment by maartenba** [comment] 2016-04-04 13:55
Can you provide some logs? NuGet.Server should be able to handle these without issue.

**Comment by NagarajMasub** [comment] 2016-04-05 08:55
The V2 feed at 'http://nuget.syncfusion.com/windows-forms/FindPackagesById()?Id='Syncfusion.Diagram.Windows40'' returned an unexpected status code '404 Not Found' we are getting this type of error

**Comment by maartenba** [comment] 2016-04-05 14:05
@emgarten This looks like the `Id` vs `id` issue?

**Comment by NagarajMasub** [comment] 2016-04-07 05:49
https://github.com/NuGet/Home/files/185950/NuGetLog.txt , please find the log file. i need to provide v2 and v3 link as like in myget
![image](https://cloud.githubusercontent.com/assets/18211481/14341820/947e9070-fcb2-11e5-9cfb-637244cab121.png)

**Comment by NagarajMasub** [comment] 2016-04-08 06:14
Can i get any update on this..?

**Comment by maartenba** [comment] 2016-04-08 14:00
From the log it seems the server is incorrectly treated as a V3 feed. Can you upgrade to the latest NuGet extension? http://dist.nuget.org/index.html

Closing as duplicate of https://github.com/NuGet/NuGetGallery/issues/2844

**Closed by maartenba** 2016-04-08 14:00 UTC

**Comment by NagarajMasub** [comment] 2016-04-08 15:03
is it need to update the extention in client machine or server

**Comment by maartenba** [comment] 2016-04-08 15:04
Client
