### ISSUE TITLE
Cannot install "Validator" and "ByteBlast.Validator" packages from nuget.org

### ISSUE THREAD

**Issue by chyuck** [NuGet/NuGetGallery#2352] opened 2015-02-01 18:50 UTC
If I use VS 2013 Package Manger, it can find packages but when i click "Install" it returns "The remote server returned an error: (504) Gateway Timeout." error.

If I use VS 2013 Package Manger Console
PM> Install-Package Validator
The source at nuget.org [https://www.nuget.org/api/v2/] is unreachable. Falling back to NuGet Local Cache at C:\Users\Andrey\AppData\Local\NuGet\Cache
Install-Package : Unable to find package 'Validator'.
At line:1 char:1
+ Install-Package Validator
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 

I tried other packages and it worked as expected.

**Comment by ChrisSfanos** [comment] 2015-04-01 21:00
Thanks for posting - we will analyze the issue and see if we can determine a root cause.  We will also look to improve the client against these types of failures - thanks!

**Comment by RanjiniM** [comment] 2015-04-22 19:00
This can't be reprod anymore. In general we have some storage/ CDN issues and that is tracked through https://github.com/NuGet/NuGetGallery/issues/2353 so closing this one.

**Closed by RanjiniM** 2015-04-22 19:00 UTC
