### ISSUE TITLE
Total downloads bug in packages page

### ISSUE THREAD

**Issue by UkrGuru** [NuGet/NuGetGallery#8626] opened 2021-06-08 07:00 UTC
### Describe the bug
Total downloads incorrect value long time.

Total downloads incorrect value in packages page (https://www.nuget.org/packages?q=ukrguru)
Total downloads incorrect value in Visual Studio (Manage Packages for Solution)

Total downloads actually in Package details only! (https://www.nuget.org/packages/UkrGuru.WebJobs/)

### To Reproduce
Open links https://www.nuget.org/packages?q=ukrguru
Then https://www.nuget.org/packages/UkrGuru.WebJobs/
Compare Total downloads values

### Screenshots
![image](https://user-images.githubusercontent.com/53341568/121363182-5ddfc200-c93f-11eb-84df-379e9e05cc77.png)
![image](https://user-images.githubusercontent.com/53341568/121138361-47067600-c840-11eb-9006-ceb6ce83a1ea.png)

**Comment by skofman1** [comment] 2021-06-21 19:15
@UkrGuru , thanks for reporting! The cause for the discrepancy was a live-site incident that caused download counts to not get updated in search results. This is fixed now.

**Closed by skofman1** 2021-06-21 19:15 UTC
