### ISSUE TITLE
Provide capability to filter on .NET Core & .NET Framework when searching

### ISSUE THREAD

**Issue by tomkerkhove** [NuGet/NuGetGallery#4502] opened 2017-08-03 07:02 UTC
Provide capability to filter on .NET Core & .NET Framework when searching since I'm only interested in one of both for certain scenarios

![screenshot_1](https://user-images.githubusercontent.com/4345663/28909829-6952f7b6-782a-11e7-834e-e81cd25a46a7.png)

**Comment by skofman1** [comment] 2017-08-09 14:13
This is duplicate of: https://github.com/NuGet/NuGetGallery/issues/3098

**Closed by skofman1** 2017-08-09 14:13 UTC
