### ISSUE TITLE
Only method to confirm ownership of a package is through an email

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3400] opened 2016-12-06 01:47 UTC
When you are added as an owner of a package, the only method to accept the ownership is through a link sent in an email. There should be an easy way to accept ownership on the website. It could be a page that shows a list of all packages that you were added as an owner to with an easy button to click.

**Comment by skofman1** [comment] 2016-12-30 20:19
Duplicate of: https://github.com/NuGet/NuGetGallery/issues/1131

**Closed** 2016-12-30 20:20 UTC
Labels: Area: Gallery UI, ClosedAs - Duplicate, Type:Feature, Up for Grabs
