### ISSUE TITLE
[Redesign] Package Statistics or Package Version Statistics pages without a "groupby" in the query is empty

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#4133] opened 2017-06-14 18:02 UTC
Notice that there is no checkboxes:
https://preview-dev.nugettest.org/stats/packages/BaseTestPackage
https://preview-dev.nugettest.org/stats/packages/BaseTestPackage/1.0.0

The page works as expected for:
https://preview-dev.nugettest.org/stats/packages/BaseTestPackage?groupby=Version
https://preview-dev.nugettest.org/stats/packages/BaseTestPackage/1.0.0?groupby=Version

This issue does not appear on live:
https://www.nuget.org/stats/packages/BaseTestPackage

**Comment by ryuyu** [comment] 2017-06-15 00:21
Closed as duplicate of https://github.com/NuGet/NuGetGallery/issues/4174

**Closed by ryuyu** 2017-06-15 00:21 UTC
