### ISSUE TITLE
Gallery keeps using the wrong casing of package id.

### ISSUE THREAD

**Issue by ghost** [NuGet/NuGetGallery#1260] opened 2013-06-22 13:19 UTC
For the NuGet.Core package, we made a mistake in version 1.6.0 by setting the id to 'Nuget.Core' (lowercase 'g'). We have corrected it a long time ago and all recent package uploads have the correct casing of NuGet.Core. 

However, the gallery is still not correcting it, both on the details page and in the feed. 

https://nuget.org/packages/Nuget.Core/2.5.0

https://nuget.org/api/v2/Packages()?$filter=tolower(Id)%20eq%20'nuget.core'%20and%20IsLatestVersion

**Comment by skofman1** [comment] 2016-12-30 21:09
Duplicate of: https://github.com/NuGet/NuGetGallery/issues/3349

**Closed by skofman1** 2016-12-30 21:09 UTC
