### ISSUE TITLE
NuGet.Server background tasks causes nuget source to misbehave (the cache index file somehow gets corrupted)

### ISSUE THREAD

**Issue by niklaskallander** [NuGet/NuGetGallery#3277] opened 2016-10-13 14:19 UTC
Hi,

We've been struggling with an issue in the NuGet.Server repo/nuget package for a while now. 

We push packages to our local nuget source quite frequently and we may push packages from several machines at any given time. But, every few days or so the cache index file gets corrupted (or so it seems) making package listing/download fail. Pushing new packages still works fine but we can't list or download any existing packages from the nuget source.

To temporarily overcome the issue we found that we could simply delete the cache index file and recycle the application pool.

To permanently overcome the issue we hacked in the NuGet.Server code-base and disabled background tasks in the ServerPackageRepository by setting `_runBackgroundTasks` to `false` at: https://github.com/NuGet/NuGet.Server/blob/master/src/NuGet.Server/Infrastructure/ServerPackageRepository.cs#L56

It won't fix the underlying issue but we'd really like an application setting to let us disable the background tasks without hacking in the code-base and building our own dll (as we don't need the background tasks in the first place).

If you prefer a pull-request (for the application setting) we'd welcome some advice on how to proceed.

Thanks!

**Comment by skofman1** [comment] 2016-10-13 22:30
A PR will be most welcome. You can always read up on GitHub and pull requests here: https://help.github.com/categories/collaborating-with-issues-and-pull-requests.

You can add code that exposes RunBackgroundTasks as a configuration setting. I suggest following the example of other settings, like: https://github.com/NuGet/NuGet.Server/blob/master/src/NuGet.Server/Infrastructure/ServerPackageRepository.cs#L671

**Comment by niklaskallander** [comment] 2016-10-14 10:37
Thanks!

However, we ran into the same issue again yesterday (after two-three weeks error-free). There seem to be some synchronicity issue in the logic modifying the cache file -OR- something else completely.

I've created a pull-request for adding a setting to enable/disable file system monitoring (e.g. not all the background tasks). 

See: https://github.com/NuGet/NuGet.Server/pull/19

After going through the code once more I found the other background tasks which seem to be rather useful/important. The thing we wanted to disable in the first place was the file system watcher which the above pull-request should take care of.

**Comment by ryuyu** [comment] 2016-10-18 19:21
PR was merged so issue is closed. Please reopen to continue discussion if necessary. Thanks!

**Comment by yishaigalatzer** [comment] 2016-12-20 22:07
I'm re-opening. I believe that this fix is not good enough, it introduces an unnecessary configuration value to overcome a bug in the product. The configuration will only be picked up by one (or a few) customer while plaguing all others.

We should fix the underlying bug proper and then ship the product (we can debate if the switch needs to stay or not on this thread)

**Comment by niklaskallander** [comment] 2016-12-21 05:41
@yishaigalatzer Thanks for considering this an actual bug! 

If the bug is solved I'd argue that the switch loses some, if not most, of its value. However, in our (my company's) scenario/setup, file system monitoring only gives the product more complexity, that we don't need. Since we turned it off a couple months ago we've been free from problems with nuget.server (no new issues have come to light). Prior to our fix, nuget.server caused us major headaches at least once a week.

I believe the switch should stay as it enables you to turn off a feature you might not need. A feature that also increases the complexity of the product, which in turn increases the likelihood of (new) bugs.

Besides, the switch is rather invisible to users/customers that don't care about it as it defaults to enable file system monitoring if it is not found (same behavior as if the switch was removed entirely). I don't believe that is to plague customers, maintainers however...

**Comment by yishaigalatzer** [comment] 2016-12-21 06:48
Im ok with leaving it in after we fix the bug

**Comment by joelverhagen** [comment] 2016-12-21 18:32
Hey @niklaskallander, could you provide any/all details you can think of concerning the cache index file corruption? I'd like to try to reproduce the issue locally and fix the root cause.

Did the corruption seem to only happen after a certain period of time?
Did it seem to be related to app restarts?
Does it seems related to package pushes occurring?
You're hosting NuGet.Server in IIS, correct?
What version of NuGet.Server are you using?

**Comment by joelverhagen** [comment] 2016-12-21 18:50
Also, what exception were you encountering? Did you happen to note what the cache file looked like?

**Comment by niklaskallander** [comment] 2016-12-21 18:58
@joelverhagen 

Although the issue occurred sporadically without any apparent reason, we did find one pattern for some of the occurrences. Sometimes after a package push we took a local copy of the package from the file system directory to verify its content. After such a file copy (ctrl+c, ctrl+v [on to the desktop of the server]) the issue often occurred.

We monitored app/server restarts (and IIS recycles) to see if we could find any patterns, to no avail. We also disabled all default IIS recycles to see if it made any difference, but no luck there either.

I don't believe it has to do with package pushes (although we haven't vested much time testing that scenario). It might be a combination of package pushes and file copy as described above.

We're using the latest version.

We have a powershell script executed on a daily basis (early morning) to clear our nuget source from any "stale" packages. It simply deletes the packages and related directories from the file system. But we haven't seen any related patterns (as in: the issue occurs after that clean-up operation).

I can't think of anything else right now, but I'd be happy to answer any other questions as they come.

Thanks! (:

**Comment by joelverhagen** [comment] 2016-12-21 19:22
> Sometimes after a package push we took a local copy of the package from the file system directory to verify its content. After such a file copy (ctrl+c, ctrl+v [on to the desktop of the server]) the issue often occurred.

So you copied a .nupkg from `~/Packages/<ID>/<VERSION>/<ID>.<VERSION>.nupkg` to the desktop of the same machine? That's strange this would effect anything since the file system watcher is listening only to file modifications made in the packages folder.

> We have a powershell script executed on a daily basis (early morning) to clear our nuget source from any "stale" packages. It simply deletes the packages and related directories from the file system. But we haven't seen any related patterns (as in: the issue occurs after that clean-up operation).

Could you share this script as well? This is definitely suspect in my mind since the file system watcher is listened to delete events as well.

Also, what is your web.config file for your NuGet.Server? What NuGet.Server app settings do you have set?

**Comment by joelverhagen** [comment] 2016-12-21 19:47
Another question: 

> To temporarily overcome the issue we found that we could simply delete the cache index file and recycle the application pool.

It looks like there is code to [handle and delete a corrupted cache file on app-start](https://github.com/NuGet/NuGet.Server/blob/225d79fd73e152b62280810bb3e270ca005eeff4/src/NuGet.Server/Infrastructure/ServerPackageStore.cs#L59-L63). In your experience, was deleting the cache file necessary? Or did just restarting the app fix the issue?

**Comment by niklaskallander** [comment] 2016-12-21 20:14
> So you copied a .nupkg from ~/Packages/<ID>/<VERSION>/<ID>.<VERSION>.nupkg to the desktop of the same machine?
Yes.

> It looks like there is code to handle and delete a corrupted cache file on app-start. In your experience, was deleting the cache file necessary?
Yes.

On the other questions I'll have to get back to you tomorrow (as I'm not currently at the office).

**Comment by niklaskallander** [comment] 2016-12-22 08:39
@joelverhagen 

> Also, what is your web.config file for your NuGet.Server? What NuGet.Server app settings do you have set?

```
<appSettings>
  <add key="requireApiKey" value="true" />
  <add key="apiKey" value="conrab.opto.builds" />
  <add key="packagesPath" value="D:\OptoNuget\Packages" />
  <add key="allowOverrideExistingPackageOnPush" value="true" />
  <add key="ignoreSymbolsPackages" value="true" />
  <add key="enableDelisting" value="false" />
  <add key="enableFrameworkFiltering" value="false" />
</appSettings>
```

> Could you share this script as well?

```
Remove-Item "C:\Windows\Temp\NuGetScratch\" -recurse 
Get-ChildItem "D:\OptoNuget\Packages\" -dir -Recurse | Where{$_.Name -Match "\d{7}" -and $_.CreationTime -lt (Get-Date).AddDays(-7)} | Remove-Item -Recurse -Force
```

> I did some more investigation and it looks like we are missing a catch for JsonSerializationException, which can occur if there is a missing array end character.

Why would there be a missing array end character? Just curious.

Thanks!

**Comment by joelverhagen** [comment] 2016-12-22 16:53
@niklaskallander, my current thought is that a partial cache file write can occur either due to a race condition in our code of a process being terminated while writing the cache file.

**Comment by joelverhagen** [comment] 2016-12-22 20:30
I'm having a hard time reproducing the issue you have described. I have found a couple of oddities:

**`JsonSerializationException` is not handled.** Since I don't what exception is being thrown in your case, this seems like the most likely candidate. When the cache file is missing a trailing curly brace, this prevents the app from starting. As mentioned above, my guess is that cache file corruption can occur either due to a race condition in our code of a process being terminated while writing the cache file.

**Toggling file system watcher events is not synchronized.** We have code that turns on and off the file system watcher events during certain operations (e.g. adding a package, handling a package in the drop folder, clear cache). This means that we clear cache more frequently that we have to.

I have done some stress tests on NuGet.Server (lots of pushes, listing of packages, and increased background job frequency) and the only weird behavior I can see is periodic cache rebuilds due to the file watcher events not being synchronized. I've not seen any corrupted cache file.

Would it be possible to look back in your web server logs and see if the exception message is still around?

This is the exception I see:

```
Unexpected end when deserializing array. Path '[0]', line 1, position 1510.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(JsonReader reader, JsonContract contract, Object currentObject, String message)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at NuGet.Server.Infrastructure.JsonNetPackagesSerializer.Deserialize(Stream stream)
   at NuGet.Server.Infrastructure.ServerPackageStore.Load()
   at NuGet.Server.Infrastructure.ServerPackageStore..ctor(IFileSystem fileSystem, String fileName)
   at NuGet.Server.Infrastructure.ServerPackageRepository..ctor(String path, IHashProvider hashProvider, ILogger logger)
   at NuGet.Server.DefaultServiceResolver..ctor()
   at NuGet.Server.DataServices.NuGetRoutes.Start()
```

Also, I would suggest you avoid manually deleting packages from the file system with that PowerShell script. I tried this out and ran into exceptions in the cache rebuild and drop directory handling code paths (however, no problem that caused a bad cache file). `nuget.exe delete` (which uses the package delete HTTP endpoint) is the recommended way to remove packages from NuGet.Server.

Thank you for the time you've already given to helping me investigate this.

**Comment by niklaskallander** [comment] 2016-12-23 11:21
@joelverhagen 

> Would it be possible to look back in your web server logs and see if the exception message is still around?

I might have been unclear when I reported this issue. We're not receiving any exceptions, we just can't get any/some packages from our source when the issue occur. It's as if nuget.server just lost track of them although they're right there on disk. The app always continue to run just fine, and we can push new packages to the source. The missing packages, however, never re-appear unless we delete the cache file and recycle the application pool.

Regarding web server logs, I'm not really sure where to look? Nuget.server seem to use a TraceLogger by default, which doesn't seem to persist the entries anywhere? We've modded this behavior a bit to use file logging via log4net instead (but we've never seen any exceptions in the generated files). 

The log mod is simply done by replacing the default service resolver (with a near "copy/paste"-version) and injecting our own logger into the `ServerPackageRepository`:
```
public class OptoServiceResolver : IServiceResolver
{
    private readonly IHashProvider _hashProvider;
    private readonly IPackageAuthenticationService _packageAuthenticationService;
    private readonly IServerPackageRepository _packageRepository;
    private readonly IPackageService _packageService;
    private readonly OptoLogger _logger;

    public OptoServiceResolver()
    {
        _logger = new OptoLogger();

        _logger.Log(LogLevel.Info, "Initializing the service resolver.");

        _hashProvider = new CryptoHashProvider(Constants.HashAlgorithm);

        _packageRepository = new ServerPackageRepository(PackageUtility.PackagePhysicalPath, _hashProvider, _logger) {Logger = _logger};

        _packageAuthenticationService = new PackageAuthenticationService();

        _packageService = new PackageService(_packageRepository, _packageAuthenticationService);
    }

    public object Resolve(Type type)
    {
        _logger.Log(LogLevel.Info, $"Resolving object of type: '{type.FullName}'.");

        if (type == typeof(IHashProvider))
        {
            return _hashProvider;
        }

        if (type == typeof(IServerPackageRepository))
        {
            return _packageRepository;
        }

        if (type == typeof(IPackageAuthenticationService))
        {
            return _packageAuthenticationService;
        }

        if (type == typeof(IPackageService))
        {
            return _packageService;
        }

        return null;
    }
}
```

> I would suggest you avoid manually deleting packages from the file system with that PowerShell script. 

Yes, we'll probably remove the script soon anyway, as we want to move away from pushing the packages until we actually know that we have to keep them. We're still polishing our build/release pipeline.

**Comment by joelverhagen** [comment] 2016-12-27 16:10
> We're not receiving any exceptions, we just can't get any/some packages from our source when the issue occur. It's as if nuget.server just lost track of them although they're right there on disk. The app always continue to run just fine, and we can push new packages to the source. The missing packages, however, never re-appear unless we delete the cache file and recycle the application pool.

Oh, I see. Thank you for the additional information! Did you notice where on disk these missing packages were? We they unextracted in the root of the packages directory? Or we they in `<ID>/<version>` subdirectories?

**Comment by joelverhagen** [comment] 2016-12-27 17:30
@niklaskallander, don't worry about answering any more of my information-gathering questions above. I found the issue 😌.

**Closed** 2016-12-27 17:45 UTC

**Comment by niklaskallander** [comment] 2016-12-28 13:39
@joelverhagen Nice work!

Just wondering whether your findings also cover the case when only a few (versions of a few) packages go missing (and not all but one)?
