### ISSUE TITLE
Search service treat versions as case sensitive strings

### ISSUE THREAD

**Issue by ptrstpp950** [NuGet/NuGetGallery#4583] opened 2017-08-21 07:23 UTC
Today I found in my build logs that: could not retrieve data from 'https://www.nuget.org/api/v2/Packages(Id='microsoft.azure.servicebus',Version='1.0.0-rc1')'
When I change package version into 1.0.0-RC1, it starts working correctly.

The error doesn't exist last week, so I suspect that upgrade made a change

**Comment by joelverhagen** [comment] 2017-08-21 16:10
Thanks for reporting this @ptrstpp950. Could you provide the exact package ID and version that succeeded before in a case-insensitive manner? Also, what time did this successful query occur? If you could provide some CI logs that mention this NuGet URL or some other log providing these three details, it would help a whole lot. 

I've dug into the root cause here and it seems be due to that fact that our search service, which sits behind the NuGet.org gallery, processes ID in a case insensitive way but version in a case sensitive way. This came as a surprise to be since almost all other components in the NuGet world treat versions as case insensitive.

ID analysis:
https://github.com/NuGet/NuGet.Services.Metadata/blob/bff7b323a6e647e94e380770657d3ce71cc88e94/src/NuGet.Indexing/IdentifierKeywordAnalyzer.cs#L12
```csharp
return new LowerCaseFilter(new KeywordTokenizer(reader));
```

Version analysis:
https://github.com/NuGet/NuGet.Services.Metadata/blob/bff7b323a6e647e94e380770657d3ce71cc88e94/src/NuGet.Indexing/VersionAnalyzer.cs#L12
```csharp
return new SemanticVersionFilter(new KeywordTokenizer(reader));
```

**Comment by ptrstpp950** [comment] 2017-08-21 18:51
I provide a link in issue
You can try
https://www.nuget.org/api/v2/Packages(Id='microsoft.azure.servicebus',Version='1.0.0-RC1') -working
And
https://www.nuget.org/api/v2/Packages(Id='microsoft.azure.servicebus',Version='1.0.0-rc1') - causes error

I can check logs tomorrow cause I'm at home now, but I'm almost sure that it was working last week

**Comment by joelverhagen** [comment] 2017-08-22 00:24
In addition to those logs, could you provide the other following information:

1. What type of project are you restoring? packages.config? project.json? PackageReference?
1. Could you provide the project file that contains the reference to Microsoft.Azure.ServiceBus?

**Comment by ptrstpp950** [comment] 2017-08-22 07:05
1.  I was restoring paket.config. 
2. It is an internal package, created by a project with PackageReferences

**Comment by joelverhagen** [comment] 2017-11-21 20:04
This issue will resolved with two sub-items:
Step 1: https://github.com/NuGet/NuGetGallery/issues/5052
Step 2: https://github.com/NuGet/NuGetGallery/issues/5051

**Comment by joelverhagen** [comment] 2018-02-12 23:03
This is fixed in PROD. Thanks again for the report.

**Comment by joelverhagen** [comment] 2019-09-25 23:34
This is fixed in PROD now.

**Closed** 2019-09-25 23:34 UTC
Labels: Area: Search, Priority - 2, Type:Bug, Verified-Dev, Verified-Int, Verified-Prod
