### ISSUE TITLE
V3 monitoring pipeline's MonitoringProcessor is slow

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#5267] opened 2018-01-11 19:03 UTC
We had a lot of activity on V3 this morning and the `MonitoringProcessor` has fallen behind (further than any of our other jobs). I believe this is due to some issue with making many many duplicate web requests and waiting on them individually, but it's not clear. There need to be some performance improvements made to the job so it can keep up.

**Comment by skofman1** [comment] 2018-08-24 00:19
This is a duplicate of: https://github.com/NuGet/NuGetGallery/issues/6327

**Closed by skofman1** 2018-08-24 00:19 UTC
Labels: Area: Monitoring & Alerting, Priority - 3
