### ISSUE TITLE
[Redesign] Stats Page doesn't show select options without query parameters

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#4153] opened 2017-06-14 22:06 UTC
If you access http://preview-dev.nugettest.org/stats/packages/newtonsoft.json the page is empty.

In nuget.org: https://www.nuget.org/stats/packages/newtonsoft.json we see filter options(Version, client...)

I think we should default the route for `/stats/packages/<id>` should be `stats/packages/<id>?groupby=Version`

**Comment by scottbommarito** [comment] 2017-06-14 22:07
duplicate of https://github.com/NuGet/NuGetGallery/issues/4133

**Closed by scottbommarito** 2017-06-14 22:07 UTC
