### ISSUE TITLE
Locked out, unable to convert nuget.org account to use Microsoft sign in

### ISSUE THREAD

**Issue by adamjcooper** [NuGet/NuGetGallery#7415] opened 2019-08-05 17:05 UTC
### Describe the bug

Our corporate nuget.org account username is "accusoft". This is currently a nuget.org account, not a Microsoft account.

We can sign in using our NuGet.org account, but after signing in we are shown the home page with a warning banner telling us we need to go to Account Settings and switch to using a Microsoft account to sign in. However, we can't actually open our account settings. In fact, nearly the entire UI of the home page is disabled (links don't work, cursor changes to indicate a clickable link or text field in strange places, etc.). 

After signing in via NuGet.org, we've tried manually navigating to https://www.nuget.org/account, but this simply redirects back to the home page.

We seem to be locked out of our account, without any way forward to convert to using a Microsoft account for sign in.

### To Reproduce

1. Navigate to https://www.nuget.org (using private/incognito mode to ensure no cookies are set)
2. Click the "sign in" link in the top right
3. Because we do not yet have a Microsoft account setup, click "Sign in using NuGet.org account"
4. Sign in with our username and password
5. Observe that we are signed in and see this at the top of the page when it loads:

![image](https://user-images.githubusercontent.com/443020/62481472-85ccd000-b780-11e9-929a-76ea2930b178.png)

6. Try to click the "Account Settings" link and observe it does not function. Try doing anything significant on this page and notice it does not function (open the profile menu in top right, click on links in top nav bar, etc.).
7. Manually navigate to https://www.nuget.org/account. Observe that the account page does not load. Instead, the home page is loaded. 

### Expected behavior
We should be able to sign in with our NuGet.org account and edit our account settings to switch over to using a Microsoft account.

### Screenshots
![image](https://user-images.githubusercontent.com/443020/62481598-d6442d80-b780-11e9-9a58-e22b17f27db0.png)

![image](https://user-images.githubusercontent.com/443020/62481626-ea882a80-b780-11e9-9ba1-23d03e5ba7e6.png)

![image](https://user-images.githubusercontent.com/443020/62481662-068bcc00-b781-11e9-9f61-24d38b0e52d7.png)

![image](https://user-images.githubusercontent.com/443020/62481717-3044f300-b781-11e9-8bb5-393e672fa8c8.png)

Additionally, manually navigating to https://www.nuget.org/account does not load the account details page. Instead, replies with an HTTP 302, redirecting to the (still non-functional) home page.

**Comment by skofman1** [comment] 2019-08-07 16:13
@adamjcooper , sorry for the slow response. Usually users reach out to us with this kind of issues via support@nuget.org

When you log-in with a password, you are supposed to get a pop-up allowing you to change to MSA/AAD account. Looks like this:

![image](https://user-images.githubusercontent.com/16807822/62639026-846fe480-b8f3-11e9-962a-86597447904a.png)

Perhaps your browser blocks the pop-up?

**Comment by adamjcooper** [comment] 2019-08-07 19:07
Thanks @skofman1, I'm definitely not seeing that pop-up. I've tried with both Chrome and Safari and have disabled extensions and content blockers.

Would you like me to start an email thread? Happy to move the discussion there.

**Comment by adamjcooper** [comment] 2019-08-07 19:17
Using dev tools in a Chrome Incognito window, I can see modal content present in the DOM, it just isn't visible on the screen for me:

![image](https://user-images.githubusercontent.com/443020/62651201-75565a00-b926-11e9-9ccf-6bb9725f783b.png)

**Comment by adamjcooper** [comment] 2019-08-07 19:28
I might be wrong, but it looks like your modal div and the underlying "curtain" are not having their CSS attributes correctly mutated. For example, I notice that the div `#popUpModal` has a CSS `.fade` class assigned to it, with an `opacity` of `0`: 

![image](https://user-images.githubusercontent.com/443020/62651780-c3b82880-b927-11e9-941c-d8f07cc7928c.png)

If I change the class to `.fade.in` (discovered in your `site.min.css` file), or just manually change its `opacity` to `100`, then I can see the dialog:

![image](https://user-images.githubusercontent.com/443020/62651901-0974f100-b928-11e9-8294-83d598d3ef01.png)

**Comment by adamjcooper** [comment] 2019-08-07 19:32
Now that I can see the dialog contents, it looks like we already have a "linked Microsoft account" which we should sign in with.

**Comment by ryuyu** [comment] 2019-08-07 19:33
Hey @adamjcooper 
Thanks for reporting this!
I'm looking into this now and it looks like it might have been a regression with a jquery upgrade.

Hopefully, we will have a fix out for this soon once i identify the root cause.

Thanks again for the help.

**Comment by adamjcooper** [comment] 2019-08-07 19:48
Thanks @ryuyu and @skofman1! 

After consulting with our IT department to get the correct credentials, I was able to sign in with our already-associated Microsoft account. As such, we are no longer "locked out" as I originally claimed.

However, as you mentioned @ryuyu, this looks like a UI bug that may affect others. I defer to you all as to whether you think this issue is important enough that it needs to be kept open or not.

Thanks again.

**Comment by ryuyu** [comment] 2019-08-14 22:16
Fix for this should now be live. Thanks!

**Closed by ryuyu** 2019-08-14 22:16 UTC
Labels: Area: Gallery UI, Customer Issue, Type:Bug

**Comment by mwpowellhtx** [comment] 2024-07-02 04:39
Having some problems logging in. Not sure related to this issue or not... 
1. Claiming I am "signed in" when I am pretty sure that "I am not".
1. After a series of prompts, I am getting prompted to create another account, because somehow my credentials "do not exist".

Is something going on back end? The identify database or server or something is offline and rejecting the sequence?

I assure you, [_I have an account_](https://nuget.org/profiles/mwpowellhtx), I have published MANY packages, some fairly recently actually.
