### ISSUE TITLE
[Package Signing] Fail fast on cert mismatch upon upload/push – make the SHA1 hash check synchronous upon upload/push

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#6008] opened 2018-05-30 17:41 UTC
a.	When the package cert does not match with registered/required (for MSFT) certs
b.	When no cert is registered and signed package is pushed
*For a & b, if it’s an upload, show the error message upon upload even before submit

**Comment by joelverhagen** [comment] 2018-07-31 21:51
Duplicate of https://github.com/NuGet/NuGetGallery/issues/6181.

**Closed by joelverhagen** 2018-07-31 21:51 UTC
Labels: Area: Gallery UI, Area: Validation, ClosedAs - Duplicate, Type:Feature
