### ISSUE TITLE
[NuGet.org Bug]: china access api.nuget.org redirect to nuget.cdn.azure.cn ResourceNotFound

### ISSUE THREAD

**Issue by godkoten** [NuGet/NuGetGallery#9335] opened 2022-12-23 18:48 UTC
### Impact

I'm unable to use NuGet.org

### Describe the bug

china access api.nuget.org redirect to nuget.cdn.azure.cn ResourceNotFound

### Repro Steps

Normal: https://api.nuget.org/v3/catalog0/data/2022.12.22.18.59.52/altv.net.client.13.0.12.json

ResourceNotFound: https://nuget.cdn.azure.cn/v3/catalog0/data/2022.12.22.18.59.52/altv.net.client.13.0.12.json

### Expected Behavior

Normal access

### Screenshots

![ff1](https://user-images.githubusercontent.com/27775356/209393536-e7031266-2cf3-4b51-ba57-bb6313bfd78f.png)
![ff2](https://user-images.githubusercontent.com/27775356/209393556-4ddda7b0-c75e-47ee-9107-d0327982eda5.png)

**Comment by joelverhagen** [comment] 2022-12-23 21:35
Hello, this is a documented gap in our API (https://learn.microsoft.com/en-us/nuget/api/catalog-resource) and a known issue.

We have a tracking issue here: https://github.com/NuGet/NuGetGallery/issues/4949

One possible workaround would be to identify an IP address for `api.nuget.org` outside of China and set up a `hosts` file override. This is not a recommended long term solution since your performance and availability of other api.nuget.org requests namely NuGet restore will not be as good.

**Comment by joelverhagen** [comment] 2022-12-23 21:36
Closing as a duplicate of https://github.com/NuGet/NuGetGallery/issues/4949.

**Closed by joelverhagen** 2022-12-23 21:36 UTC
Labels: Type:Bug
