### ISSUE TITLE
[Bug]:  HTML tags supported in CommonMark not rendered in nuget.org documentation page

### ISSUE THREAD

**Issue by aus10code** [NuGet/NuGetGallery#9186] opened 2022-08-06 08:27 UTC
### NuGet Product Used

NuGet.exe

### Product Version

6.0

### Worked before?

Not sure

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

html/css not supported in readme file when uploaded to [Nuget.org](https://www.nuget.org/packages/austen.ConsoleHelperLibrary/)

The [documentation](https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#supported-markdown-features) says it supports CommonMark compliant Markdown.

when using [spec.commonmark.org](https://spec.commonmark.org/dingus/?text=%3Ch1%20align%3D%22center%22%3E%20ConsoleLibraryHelper%20%3C%2Fh1%3E%0A%0A%3Cp%20align%3D%22center%22%3E%20%3Ca%20href%3D%22https%3A%2F%2Fwww.nuget.org%2Fpackages%2Fausten.ConsoleHelperLibrary%2F%22%20alt%3D%22%22%3E%20%3Cimg%20src%3D%22https%3A%2F%2Fimg.shields.io%2Fnuget%2Fv%2Fausten.ConsoleHelperLibrary%22%20%2F%3E%3C%2Fa%3E%20%3Ca%20href%3D%22https%3A%2F%2Fwww.nuget.org%2Fpackages%2Fausten.ConsoleHelperLibrary%2F%22%20alt%3D%22%22%3E%20%3Cimg%20src%3D%22https%3A%2F%2Fimg.shields.io%2Fnuget%2Fdt%2Fausten.ConsoleHelperLibrary%22%20%2F%3E%3C%2Fa%3E%20%3Ca%20href%3D%22https%3A%2F%2Fbadgen.net%2Fbadge%2Ficon%2Fgithub%3Ficon%3Dgithub%26label%22%20alt%3D%22%22%3E%20%3Cimg%20src%3D%22https%3A%2F%2Fbadgen.net%2Fbadge%2Ficon%2Fgithub%3Ficon%3Dgithub%26label%22%20%2F%3E%3C%2Fa%3E%20%3Ca%20href%3D%22https%3A%2F%2Fimg.shields.io%2Fgithub%2Flicense%2Faus10code%2FConsoleHelperLibrary%22%20alt%3D%22%22%3E%20%3Cimg%20src%3D%22https%3A%2F%2Fimg.shields.io%2Fgithub%2Flicense%2Faus10code%2FConsoleHelperLibrary%22%20%2F%3E%3C%2Fa%3E%20%3C%2Fp%3E) with the following code it works on the generator but not on [Nuget.org](https://www.nuget.org/packages/austen.ConsoleHelperLibrary/) as shown by my package

This readme correctly displays on [Github](https://github.com/aus10code/ConsoleHelperLibrary). I'm not sure if Nuget.org uses the same parser

**image of issue below**

![image](https://user-images.githubusercontent.com/62197117/183241194-8550db9c-aa1c-49a9-8123-b4c4727678e1.png)

**Comment by loic-sharma** [comment] 2022-08-09 02:13
This is a duplicate of https://github.com/NuGet/NuGetGallery/issues/8644

**Comment by aus10code** [comment] 2022-08-09 07:11
> This is a duplicate of #8644

Indeed it is.

I tried finding an existing ticket but I guess I didn't use any matching keywords.

**Comment by joelverhagen** [comment] 2022-08-25 14:01
We'll close this in light of https://github.com/NuGet/NuGetGallery/issues/8644. Thanks!

**Closed by joelverhagen** 2022-08-25 14:01 UTC
Labels: Type:Bug, Triage:Untriaged
