### ISSUE TITLE
Improve push error message when a package is not compliant with Microsoft policies

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#6646] opened 2018-11-09 23:00 UTC
Repro steps:
1. apply the Microsoft team policy to an account
2. push a non-compliant package using nuget push
3. Expected - a good error message explaining what's wrong
4. Actual
```
C:\Users\karann\source\repos\LicenseTest\PackageA\bin\Debug>nuget push BasicMathNew.0.0.1.nupkg -Src https://api.nuget.org/v3/index.json -apikey ~~redacted~~
Pushing BasicMathNew.0.0.1.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  BadRequest https://www.nuget.org/api/v2/package/ 2076ms
Response status code does not indicate success: 400 (Bad Request).
```

**Comment by skofman1** [comment] 2018-11-20 20:44
This was caused by a bug that is now fixed.

**Closed by skofman1** 2018-11-20 20:44 UTC
