### ISSUE TITLE
500 Internal Server Error with UNC URLs in package metadata

### ISSUE THREAD

**Issue by dac11** [NuGet/NuGetGallery#7414] opened 2019-08-05 13:55 UTC
We are using NuGet.Server v3.2.1.0. During startup the server returns "500 Internal Server Error" to every client which wants to access the nuget server. The Server needs about a minute to start up.

I did disable FileSystemMonitoring in Webconfig and set initialCacheRebuildAfterSeconds =1. Now the "500 Internal Server Error" is returned for only about 10 Secondes.

Is this by design or a bug? Everyone thinks the server is broken but it is only waking up.

**Comment by dac11** [comment] 2019-08-05 14:09
Iam getting following Stracktrace while debugging or making an request from localhost
<m:message>Exception has been thrown by the target of an invocation.</m:message>

<m:type>System.Reflection.TargetInvocationException</m:type>

<m:stacktrace> at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Web.Http.OData.Query.ODataQueryOptions.LimitResults(IQueryable queryable, Int32 limit, Boolean& resultsLimited) at System.Web.Http.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings) at NuGet.Server.V2.Model.QueryResult`1.ExecuteQuery(IQueryable`1 queryable, ODataQueryOptions`1 queryOptions) at NuGet.Server.V2.Model.QueryResult`1.GetInnerResult() at NuGet.Server.V2.Model.QueryResult`1.<ExecuteAsync>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()</m:stacktrace>


-<m:internalexception>

<m:message>This operation is not supported for a relative URI.</m:message>

<m:type>System.InvalidOperationException</m:type>

<m:stacktrace> at System.Uri.GetComponents(UriComponents components, UriFormat format) at NuGet.Server.Core.DataServices.PackageExtensions.AsODataPackage(IServerPackage package, ClientCompatibility compatibility) at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() at System.Linq.Buffer`1..ctor(IEnumerable`1 source) at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext() at System.Linq.Enumerable.<SkipIterator>d__31`1.MoveNext() at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext() at System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext() at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Web.Http.OData.Query.TruncatedCollection`1..ctor(IQueryable`1 source, Int32 pageSize) at System.Web.Http.OData.Query.ODataQueryOptions.LimitResults[T](IQueryable`1 queryable, Int32 limit, Boolean& resultsLimited)</m:stacktrace>

</m:internalexception>

**Comment by dac11** [comment] 2019-08-05 14:53
This behavior exists since v.3.0.0.0. V 2.14.2 was working fine

**Comment by joelverhagen** [comment] 2019-08-07 16:28
Could you check the icon URL, license URL, or project URLs of the packages in your feed? A minimal repro with the broken package(s) would help. Feel free to prune the .nupkg of any private information like .DLLs. I think the only part of the package that could cause this problem is one of the URLs in the .nuspec.

This code looks to be throwing the exception. My best guess is that a relative URI is somehow making it into the server and then failing to be displayed like this:
https://github.com/NuGet/NuGet.Server/blob/97e3d99ca143dc1f48da54f7a1646de6e4b7cd01/src/NuGet.Server.Core/DataServices/PackageExtensions.cs#L27-L29

**Comment by dac11** [comment] 2019-08-07 17:14
hello Joel,
Thanks for the quick reply. I did some tests.
We just use <iconUrl>. We use Icons on unc fileshare and they are displayed in nuget client.

 <iconUrl>//fileserver/Framework/NuGet/server.png</iconUrl>

I did change the URL to <iconUrl>http://code.google.com/p/autofac/logo</iconUrl> and the server is starting up fine.

Can this please be fixed in the nuget server or should we change all existing packages?

**Comment by joelverhagen** [comment] 2019-08-07 17:25
I need to investigate more about the root cause and play with UNC URLs in NuGet.Server. I'll respond back to this issue when I know more.

**Comment by dac11** [comment] 2019-08-07 17:28
Thanks a lot. I did also notice that some pictures have been deleted on unc share. In my tests there was no difference between deleted or available pictures on the fileshare.

**Comment by joelverhagen** [comment] 2019-08-07 18:16
I tried both of these formats locally:

```
//fileserver/Framework/NuGet/server.png
\\fileserver\Framework\NuGet\server.png
```

Both worked for me and were mapped to the form:
```
file://fileserver/Framework/NuGet/server.png
```

Could you determine the version of .NET Framework that you are using on the server hosting NuGet.Server?
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

Also, how are you pushing your packages to NuGet.Server? Are you dropping them in the package directory or are you pushing them from command line, e.g. `nuget.exe push`?

Could you check the `*.cache.bin` file (it's JSON) and see what the `"IconUrl"` property says for the affected package(s)?

Also, could you try making a simple console app like this and run in on the machine hosting the NuGet.Server?

```csharp
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(new Uri("//fileserver/Framework/NuGet/server.png")
                .GetComponents(UriComponents.HttpRequestUrl, UriFormat.Unescaped));

            Console.WriteLine(new Uri(@"\\fileserver\Framework\NuGet\server.png")
                .GetComponents(UriComponents.HttpRequestUrl, UriFormat.Unescaped));

            Console.WriteLine(new Uri("file://fileserver/Framework/NuGet/server.png")
                .GetComponents(UriComponents.HttpRequestUrl, UriFormat.Unescaped));
        }
    }
}
```

**Comment by dac11** [comment] 2019-08-08 14:12
Hello
We are testing  to migrate the Nugetserver from  2.8 to Version 3.3.3. For Migration  all Packages are file copied into the new local. After that the build uses the push command. The error occurs only while the server is starting up. After a couple of seconds it is working fine. Anyway the clients who first access the server will get the error
I can reproduce the error on our server and my devmachine they both use .NET Framework 4.7.2
I did further tests and the error occurs only with / and not with \. I did also check with fileshares on different machines.
Working
    <iconUrl>\\probackup2012\TFS_VS_Customizing\NuGet\PROFX_server.png</iconUrl>
		Cachefile:
"IconUrl":"\\\\probackup2012\\TFS_VS_Customizing\\NuGet\\PROFX_server.png",
not workuing
    <iconUrl>//probackup2012/TFS_VS_Customizing/NuGet/PROFX_server.png</iconUrl>
	Cachefile:
"IconUrl":"//probackup2012/TFS_VS_Customizing/NuGet/PROFX_server.png"


The result of your code is
file://fileserver/Framework/NuGet/server.png
file://fileserver/Framework/NuGet/server.png
file://fileserver/Framework/NuGet/server.png

**Comment by dac11** [comment] 2019-08-12 14:10
Sorry for the late reply. The Uri is relative during server startup. I can reproduce it with following code:
```
           Console.WriteLine(new Uri("//fileserver/Framework/NuGet/server.png",UriKind.Relative)
                .GetComponents(UriComponents.HttpRequestUrl, UriFormat.Unescaped));
```

I did following fix on dev machine and will push it to dev Environment
```
public ServerPackage(IPackage package,PackageDerivedData packageDerivedData)
        {
 Id = package.Id;
            Version = package.Version;
            Title = package.Title;
            Authors = package.Authors;
            Owners = package.Owners;
           // old IconUrl = new Uri(package.IconUrl
            IconUrl = new Uri(package.IconUrl.ToString(), UriKind.Absolute);
```
The rootcause should be the Package in Nuget.core. Iam not sure if my fix is a good fix

**Comment by joelverhagen** [comment] 2019-08-12 14:29
> The rootcause should be the Package in Nuget.core. Iam not sure if my fix is a good fix

I like your fix a lot actually. NuGet.Core is very old repository for us so we do minimal changes in that area. We have done other workarounds in NuGet.Server to make up for NuGet.Core limitations so this seems very reasonable.

I'll take a look a little deeper because I did a superficial investigation into NuGet.Core last week and got the impression that we should be parsing such URLs as absolute all the time. I must have been mistaken.

**Comment by dac11** [comment] 2019-08-12 14:41
Thanks for the explanation my knowledge about the nugetprojects is very limited. 
 I guess the fix has to be applied also to licenseurl and projecturl as well.

**Comment by dac11** [comment] 2019-08-12 15:44
Did publish the fix to the developer nugetserver. Seems running fine . Will observe it for a couple of days. 
Would be great if will be fixed in the product.

**Comment by joelverhagen** [comment] 2019-08-12 18:48
I was able to reproduce the issue. Turns out I was misunderstanding your original steps and was only testing the case where a new package is pushed to the server _after startup_, not the case when the package is already pushed and the server is reading the information from the cache.

It looks like things behave inconsistently for URLs of the following shape:
```
//fileserver/Framework/NuGet/server.png
```

The problems seems to lie in how we deserialize the JSON cache file. We use Newtonsoft.Json to deserialize the URL properties into type `Uri`. I dug into the Newtonsoft.Json source and found this line:
https://github.com/JamesNK/Newtonsoft.Json/blob/cdf10151d507d497a3f9a71d36d544b199f73435/Src/Newtonsoft.Json/Utilities/ConvertUtils.cs#L478

Newtonsoft.Json is using <code>new Uri(input, <b>UriKind.RelativeOrAbsolute</b>)</code>. In a simple console app, I was able to confirm that this yields a relative URI for UNC paths. The strange part is that <code>new Uri(input, <b>UriKind.Absolute</b>)</code> yields an absolute URI for the same input string.

We assumed we could safely round trip a `Uri` through Newtonsoft.Json using the default serialization settings. I filed a bug about this on Newtonsoft.Json's repo but we should workaround the issue on our own:
https://github.com/JamesNK/Newtonsoft.Json/issues/2128

Here is a PR with the workaround:
https://github.com/NuGet/NuGet.Server/pull/87

Could you connect to this feed and try a prerelease build with this change?

Feed URL: https://dotnet.myget.org/F/nuget-build/api/v3/index.json
Package ID: NuGet.Server
Package Version: 3.4.0-jver-abs-2935664

**Comment by dac11** [comment] 2019-08-13 09:28
Thank you. I did download the nuget and its working fine.

**Comment by joelverhagen** [comment] 2019-08-13 18:37
NuGet.Server 3.4.1 is released with this fixed.
https://www.nuget.org/packages/NuGet.Server/3.4.1

**Closed by joelverhagen** 2019-08-13 18:37 UTC
Labels: Area: NuGet.Server, Customer Issue
