### ISSUE TITLE
Package remained verified after the organization owning the namespace was removed as owner of the package

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#6039] opened 2018-06-08 01:09 UTC
See PR: https://github.com/NuGet/NuGetGallery/pull/5984

The package is still verified after the organization owning the namespace was removed as the owner of the package. 
Observation: Everything in database seems to be cleaned.
1. The package has only one owner that is not the org or the org admin.
2. The namespace "cmaad" is reserved by the cmanutestorg
3. The ReservedNamespaceRegistrations does not have a reference to the package that is verified. 

Few UI snapshots:
![image](https://user-images.githubusercontent.com/16580006/41133712-640ae41c-6a7d-11e8-8277-302c78f0d286.png)

![image](https://user-images.githubusercontent.com/16580006/41133731-8586e776-6a7d-11e8-8947-21c0414aa193.png)

![image](https://user-images.githubusercontent.com/16580006/41133765-b43b39aa-6a7d-11e8-8727-def1ab7918da.png)

**Comment by shishirx34** [comment] 2018-06-08 17:35
Looks like the `IsVerified` flag isn't cleared from the `PackageRegistrations` table after removing organization that owns it. @scottbommarito worked on it recently to manage and cleanup registrations for namespace for org owner removal.

**Comment by shishirx34** [comment] 2018-06-08 17:40
There is a check for removing the verified flag: https://github.com/NuGet/NuGetGallery/blob/4cc71844cd5dca7edd9af36a569839f354173dca/src/NuGetGallery/Services/PackageOwnershipManagementService.cs#L159 are you sure that the package registration doesn't have any other matching/related namespace?

**Comment by shishirx34** [comment] 2018-06-08 17:57
Oh, I think I see the problem, the issue is on the same line mentioned above, however, the previous call to `RemovePackageRegistrationFromNamespace()` to remove the relevant `PackageRegistration` from `ReservedNamespace` is not `committed`, and its likely the `!packageRegistration.ReservedNamespaces.Any()` is returning `false`, thereby not removing the `IsVerified` flag, I will let @scottbommarito fix the issue, since it is likely this has far reaching effects due to the above said refactoring.

**Comment by scottbommarito** [comment] 2018-06-11 17:28
Currently `RemovePackageRegistrationFromNamespace` removes the `PackageRegistration` from the `ReservedNamespace` but does not remove the `ReservedNamespace` from the `PackageRegistration`. It needs to do both for the check you mentioned above to work.

The unit tests do not need to change because they already assume `RemovePackageRegistrationFromNamespace` does both.

**Closed** 2018-06-14 20:46 UTC
Labels: Area: Gallery UI, Priority - 1, Type:Bug, Verified-Int
