### ISSUE TITLE
ReadMe input persists on cancelling an upload

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4751] opened 2017-09-26 18:18 UTC
Repro steps:

1. Start uploading a package on Upload page
2. Cancel the upload

**Expected**: The page gets reset to its original

**Actual**: The ReadMe input persists:

![image](https://user-images.githubusercontent.com/14800916/30876787-7a520cb2-a2ac-11e7-88d9-1ecae057bd9d.png)

**Comment by anangaur** [comment] 2017-09-26 18:21
Linking https://github.com/NuGet/NuGetGallery/issues/4729

**Comment by chenriksson** [comment] 2017-09-27 18:09
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4707. Will be fixed in next deployment.

**Closed by chenriksson** 2017-09-27 18:09 UTC
Labels: Area: Gallery UI
