### ISSUE TITLE
How to create NuGet API V3 feed

### ISSUE THREAD

**Issue by DineshMuralitharan** [NuGet/NuGetGallery#2978] opened 2016-04-08 13:36 UTC
Hi ,

i have to know how to generate a api v3 links as like in myget
![image](https://cloud.githubusercontent.com/assets/18349782/14385210/d3a699c2-fdbc-11e5-8da5-5b6c877c5e03.png)

i have tried to get any online samples but i couldn't find any . can you please provide some samples how to create nuget v3 feed.

**Comment by maartenba** [comment] 2016-04-08 14:00
Closing as duplicate of https://github.com/NuGet/NuGetGallery/issues/2844

**Closed by maartenba** 2016-04-08 14:00 UTC

**Comment by DineshMuralitharan** [comment] 2016-04-08 15:08
HI,

i didn't get any samples for creating nuget v3 feed , Is it possible to provide api v3 link in NuGet.Server ..?

**Comment by maartenba** [comment] 2016-04-08 15:09
There is no support for NuGet V3 feeds. Please us the V2 feed NuGet.Server provides.

**Comment by DineshMuralitharan** [comment] 2016-04-08 15:10
any other nuget feeds provide api v3 links like myget.
