### ISSUE TITLE
Forbidden status and prompted to enter credentials when attempt to push new package with same ID as an existing one

### ISSUE THREAD

**Issue by AnotherSadGit** [NuGet/NuGetGallery#3218] opened 2016-08-28 13:28 UTC
I was attempting to push a new package to Nuget and each time was getting a Forbidden status back, and was prompted for my credentials to connect to the site.  After hours of trying to figure out the problem it turned out the issue was the ID of the new package I was attempting to push duplicated the ID of an existing package from a different author.

The error message and the prompt for credentials seems misleading in this situation.  I suggest an explicit error message, if possible, along the lines of "Unable to push the package, ID duplicates the ID of an existing package."

**Comment by shishirx34** [comment] 2016-08-30 20:21
@AnotherSadGit - Thank you for reporting, I see that the issue is reproducible with the nuget.exe. I have created another tracking issue with the Client team. Will close this bug since it is not directly actionable from the gallery.

**Comment by shishirx34** [comment] 2016-08-30 22:05
Its possible that the gallery isn't returning correct error message to the client. Reopening the bug.

**Comment by shishirx34** [comment] 2016-08-31 18:07
The forbidden result was by design and at the moment the prescribed behavior is that the client could show the returned message.

**Closed by shishirx34** 2016-08-31 18:07 UTC
