### ISSUE TITLE
NuGet stats and version history out of sync

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#6765] opened 2018-12-17 21:50 UTC
Version history for package https://www.nuget.org/packages/Graphity shows:

![image](https://user-images.githubusercontent.com/14800916/50117718-9b49b580-0202-11e9-8802-e261f0d94b3c.png)

While the stats page shows:
![image](https://user-images.githubusercontent.com/14800916/50117782-bfa59200-0202-11e9-850e-f32164be9d89.png)

**Comment by rianjs** [comment] 2018-12-18 02:55
#6764 is likely related.

**Comment by chenriksson** [comment] 2018-12-18 20:23
Closing as duplicate of #6764. I'll provide updates in that issue.

**Closed by chenriksson** 2018-12-18 20:23 UTC
