### ISSUE TITLE
[Azure Search] Use synonym mapping for improving search results

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#7122] opened 2019-05-02 00:13 UTC
We could potentially use synonym mappings for improving known search queries, for eg: searching for database could also include "sql", "nosql", "table storage" etc as the search terms. Azure search provides a way to map these keywords together using Synonym maps which could potentially be helpful.

This work can be done in the future for search improvements.

**Comment by loic-sharma** [comment] 2019-05-29 19:49
Closing as dupe of https://github.com/nuget/nugetgallery/issues/6942

**Closed by loic-sharma** 2019-05-29 19:49 UTC
Labels: Area: Search, Priority - 3
