### ISSUE TITLE
nuget.org stopped recognizing my Microsoft account

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/NuGetGallery#5021] opened 2017-11-16 23:22 UTC
I have two accounts, one @hotmail.com and one @microsoft.com. I'm pretty sure I've used @hotmail.com account to "Sign-in with Microsoft" previously on nuget.org and it worked fine.

However today I find that after I click "Sign-in with Microsoft" it no longer recognizes my account:
![image](https://user-images.githubusercontent.com/679326/32921231-a3a24548-cae1-11e7-999d-63de66bc9464.png)

After I click Connect to existing... and enter my username and password, I get this:

![image](https://user-images.githubusercontent.com/679326/32921254-c084a318-cae1-11e7-980a-5d23abea8a7a.png)

I suspect this is because I'm signed in with the wrong MS account (@microsoft.com) and it doesn't offer me to sign out or switch accounts. Perhaps it should adopt the new MS sign-in experience?

I'd be happy to assist in reproing, just ping me internally.

**Comment by KirillOsenkov** [comment] 2017-11-16 23:24
I've tried with the Incognito mode, and even after I've explicitly sign in with @hotmail.com it has the same behavior (two screens I posted above). So it's not because of @microsoft.com. Something else broke today. It was working yesterday.

**Comment by shishirx34** [comment] 2017-11-17 04:30
@KirillOsenkov - do you mind reaching out to us on support[at]nuget[dot]org with your NuGet username and associated MSA(hotmail) email address and we can look into it. Nothing has changed on our side recently with regards to MSA login, so I'd be curious to find out what broke. The @microsoft.com account won't work with the current MSA login flow, these auth only personal MSA accounts currently.

**Comment by shishirx34** [comment] 2017-11-21 01:16
Checked with @KirillOsenkov and the issue is not repro'ing again. I couldn't find any correlate able exceptions/500 requests to an auth request from 5 days ago, I suspect some kind of auth failure from MSA endpoint caused 500 in our server. I will dig more in the logs. Closing the issue for now, please feel free to re-open if you encounter this issue again.

**Closed by shishirx34** 2017-11-21 01:16 UTC
Labels: Area: Gallery UI, Type:Bug
