### ISSUE TITLE
VS2015 appears as "Unknown" in stats - client name

### ISSUE THREAD

**Issue by Daniel15** [NuGet/NuGetGallery#2383] opened 2015-03-16 06:39 UTC
Example: https://www.nuget.org/stats/packages/Microsoft.AspNet.Mvc.Core?groupby=Version&groupby=ClientName

All the "Other" downloads appear to be VS2015.

**Comment by yishaigalatzer** [comment] 2015-03-31 06:40
@Daniel15 we looked at this today. That was a cool guess, but not a correct one. Some percentage of the others is indeed VS2015 related restores/installs but not only. We are going to fix the ones that provide us we a proper `user-agent` and we let the ASP.NET 5 team know through https://github.com/aspnet/dnx/issues/1546. Once that issue is fixed a large portion of downloads will get proper tagging. We don't want to just modify the data, because any generic client that doesn't provide a user-agent falls in that category.

Closing this as duplicate of https://github.com/NuGet/Home/issues/258, as we want to track all issues at home.

@Eilon @csharpfritz

**Closed by yishaigalatzer** 2015-03-31 06:40 UTC
